- .stylelintrc.json
- express/blocks/banner/banner.css
- express/blocks/link-list/link-list.css
- express/blocks/ratings/ratings.css
- express/blocks/steps/steps.css
- express/styles/styles.css
Add few more styles to individual blocks to handle the difference between the original page and the new one:
- https://feature-convert-png2jpg--express-milo--adobecom.hlx.page/express/feature/image/convert/png-to-jpg?martech=off
> Fix spacing difference on feature/image/convert/png-to-jpg

- express/blocks/promotion/promotion.css
- express/blocks/promotion/promotion.js
- express/blocks/ratings/ratings.js
- express/scripts/utils.js
- express/scripts/utils/icons.js
Add promotion block.
- https://promotions--express-milo--adobecom.hlx.page/express/feature/video/resize
> Promotions

- express/blocks/link-list/link-list.css
Resolves: [MWPW-146267](https://jira.corp.adobe.com/browse/MWPW-146267)
Test URLs:
- Pre Migration Link: https://adobe.com/express/feature/video/convert/video-to-gif
- Before: https://main--express-milo--adobecom.hlx.page/express/feature/video/convert/video-to-gif
- After: https://mwpw-146267-link-list--express-milo--adobecom.hlx.page/express/feature/video/convert/video-to-gif?martech=off
> MWPW-146267: link-list block

- express/blocks/image-list/image-list.css
- express/blocks/image-list/image-list.js
- test/blocks/image-list/image-list.test.js
- test/blocks/image-list/mocks/body.html
- test/blocks/image-list/mocks/second-cell-no-anchor.html
- test/blocks/image-list/mocks/third-cell.html
Resolves: [MWPW-143369](https://jira.corp.adobe.com/browse/MWPW-143369)
Test URLs:
- Pre Migration Link: https://www.adobe.com/express/learn/blog/instagram-stories
- Before: https://main--express-milo--adobecom.hlx.page/express/learn/blog/instagram-stories
- After: https://rl-adobe-image-list--express-milo--adobecom.hlx.page/express/learn/blog/instagram-stories?martech=off
> MWPW-143369: image-list block

- express/blocks/ax-table-of-contents/ax-table-of-contents.css
Resolves: [MWPW-143405](https://jira.corp.adobe.com/browse/MWPW-143405)
Test URLs:
- Pre Migration Link: https://www.adobe.com/express/learn/blog/instagram-stories
- Before: https://main--express-milo--adobecom.hlx.page/express/learn/blog/instagram-stories
- After: https://mwpw-143405-table-of-contents--express-milo--adobecom.hlx.page/express/learn/blog/instagram-stories?martech=off
> MWPW-143405: Fix table-of-contents to be limited in wrapper size

- express/blocks/frictionless-quick-action/frictionless-quick-action.css
- express/blocks/frictionless-quick-action/frictionless-quick-action.js
- express/scripts/scripts.js
- express/scripts/utils.js
- test/blocks/frictionless-quick-action/frictionless-quick-action.test.js
- test/blocks/frictionless-quick-action/mocks/crop-image-quick-action.html
- test/blocks/test-utilities.js
Resolves: [MWPW-146081](https://jira.corp.adobe.com/browse/MWPW-146081)
Test URLs:
- Pre Migration Link: https://adobe.com/express/feature/image/remove-background
- Before: https://main--express-milo--adobecom.hlx.page/express/feature/image/remove-background
- After: https://MWPW-146081-fqa-block--express-milo--adobecom.hlx.page/express/feature/image/remove-background
> MWPW-146081 migrate fqa block

- express/blocks/ax-columns/ax-columns.js
- express/scripts/instrument.js
- express/scripts/scripts.js
- express/scripts/utils.js
- express/scripts/utils/content-replace.js
Test URLs:
- Before: https://main--express-milo--adobecom.hlx.page/express/colors/blue
- After: https://mwpw-150660-sprint-2-fixes-vic--express-milo--adobecom.hlx.live/express/colors/blue
> MWPW-150660 add content replace script

- express/blocks/ax-columns/ax-columns.js
- express/blocks/image-list/image-list.js
- express/blocks/template-list/template-list.js
- express/scripts/utils/decorate.js
- express/scripts/utils/icons.js
Resolves: [MWPW-142259](https://jira.corp.adobe.com/browse/MWPW-142259)
Test URLs:
- Pre Migration Link: https://adobe.com/express/ambassadors/list
- Before: https://main--express-milo--adobecom.hlx.page/express/ambassadors/list
- After: https://MWPW-142259-socialIcons--express-milo--adobecom.hlx.page/express/ambassadors/list
- Pre Migration Link: https://adobe.com/express/collaborations
- Before: https://main--express-milo--adobecom.hlx.page/express/collaborations
- After: https://MWPW-142259-socialIcons--express-milo--adobecom.hlx.page/express/collaborations
- Pre Migration Link: https://adobe.com/express/learn/blog/how-to-get-youtube-subscribers
- Before: https://main--express-milo--adobecom.hlx.page/express/learn/blog/how-to-get-youtube-subscrib …
> MWPW-142259 decorate social icons on a block level

- express/blocks/ax-columns/ax-columns.js
- express/blocks/how-to-steps-carousel/how-to-steps-carousel.css
- express/blocks/how-to-steps-carousel/how-to-steps-carousel.js
- express/scripts/scripts.js
- express/scripts/utils.js
- express/scripts/utils/location-utils.js
- test/blocks/how-to-steps-carousel/how-to-steps-carousel.test.js
Resolves: [MWPW-143367](https://jira.corp.adobe.com/browse/MWPW-143367)
Test URLs:
- Pre Migration Link: https://adobe.com/express/create/invitation/baby-shower
- Before: https://main--express-milo--adobecom.hlx.page/express/create/invitation/baby-shower
- After: https://MWPW-143367--express-milo--adobecom.hlx.page/express/create/invitation/baby-shower
> feat: MWPW-143367 | add how-to-steps-carousel block

- express/blocks/blog-posts/blog-posts.css
- express/blocks/blog-posts/blog-posts.js
- express/blocks/faq/faq.css
- express/blocks/image-list/image-list.css
- express/blocks/link-list/link-list.css
- express/blocks/link-list/link-list.js
- express/blocks/quotes/quotes.css
- express/blocks/steps/steps.css
- express/blocks/template-list/template-list.css
- express/scripts/scripts.js
- express/styles/styles.css
- express/templates/blog/blog.css
- express/templates/blog/blog.js
Gets blog working with template flow from milo. 
Important for testing: please do not bother testing the marquee, how-to-steps or template-lists on the blog pages. The marquee & how-to-steps, etc. will be migrated later and template-lists are deprecated, which is why we will not be investing much effort into them anymore (unless you see something super critical)
Resolves: [MWPW-141918](https://jira.corp.adobe.com/browse/MWPW-141918), [MWPW-143330](https://jira.corp.adobe.com/browse/MWPW-143330)
Test URLs:
- https://blog--express-milo--adobecom.hlx.live/express/learn/blog?martech=off
- https://www.adobe.com/express/learn/blog?martech=off
- https://blog--express-milo--adobecom.hlx.live/express/learn/blog/instagram-stories?martech=off
- …
> MWPW-141918 Blog Template & Blog Posts

- express/blocks/ckg-link-list/ckg-link-list.js
- express/blocks/search-marquee/search-marquee.js
- express/blocks/seo-nav/seo-nav.css
- express/blocks/template-list/breadcrumbs.js
- express/blocks/template-x/template-rendering.js
- express/blocks/template-x/template-x.css
- express/scripts/widgets/free-plan.js
Resolves: [MWPW-154536](https://jira.corp.adobe.com/browse/MWPW-154536)
Test URLs:
- Before: https://main--express-milo--adobecom.hlx.page/express/?martech=off
- After: https://gen-7-fixes--express-milo--adobecom.hlx.page/express/colors/pink?martech=off
- After: https://gen-7-fixes--express-milo--adobecom.hlx.page/express/templates/?martech=off
- After: https://gen-7-fixes--express-milo--adobecom.hlx.live/uk/express/fragments/index-featured-templates?martech=off
- After: https://gen-7-fixes-express-milo--adobecom.hlx.live/express/create/story/instagram?martech=off
- After: https://template-x--express-milo--adobecom.hlx.live/jp/express/templates/?martech=off
> Sprint 7 fixes

- 404.html
This brings 404 up to speed with Milo, loading feds
Resolves: [MWPW-143488](https://jira.corp.adobe.com/browse/MWPW-143488)
Test URLs:
- Pre Migration Link: https://adobe.com/express/nopage
- Before: https://main--express-milo--adobecom.hlx.page/express/nopage
- After: https://404--express-milo--adobecom.hlx.page/express/nopage
> MWPW-143488: 404 pages

- express/blocks/sticky-promo-bar/sticky-promo-bar.css
- express/blocks/sticky-promo-bar/sticky-promo-bar.js
- express/templates/blog/blog.css
- test/blocks/sticky-promo-bar/sticky-promo-bar.test.js
Resolves: [MWPW-143403](https://jira.corp.adobe.com/browse/MWPW-143403)
Test URLs:
- Pre Migration Link: https://adobe.com/express/learn/blog/welcome-to-adobe-spark
- Before: https://main--express-milo--adobecom.hlx.page/express/learn/blog/welcome-to-adobe-spark
- After: https://MWPW-143403--express-milo--adobecom.hlx.page/express/learn/blog/welcome-to-adobe-spark
Additional Tests: 
- Rounded: https://MWPW-143403--express-milo--adobecom.hlx.page/express/fragments/rejected-beta-promo-bar
> add sticky-promo-bar block

- express/blocks/content-toggle/content-toggle.css
- express/blocks/content-toggle/content-toggle.js
- test/blocks/content-toggle/content-toggle.test.js
Resolves: [MWPW-143344](https://jira.corp.adobe.com/browse/MWPW-143344)
Test URLs:
- Pre Migration Link: https://adobe.com/express/collaborations
- Before: https://main--express-milo--adobecom.hlx.page/express/collaborations
- After: https://MWPW-143344--express-milo--adobecom.hlx.page/express/collaborations
- https://MWPW-143344--express-milo--adobecom.hlx.page/express/experiments/ccx0110/education-challenger
> add content-toggle block

- express/blocks/pricing-cards/pricing-cards.css
- express/blocks/pricing-cards/pricing-cards.js
- express/blocks/pricing-cards/pricing-toggle.js
- express/scripts/utils/pricing.js
Resolves: [MWPW-143422](https://jira.corp.adobe.com/browse/MWPW-143422)
Test URLs:
- Pre Migration Link: https://adobe.com/express/pricing
- Before: https://main--express-milo--adobecom.hlx.page/express/pricing
- After: https://MWPW-143422-sync--express-milo--adobecom.hlx.page/express/pricing
> incorporate express changes for pricing-cards

- express/blocks/playlist/playlist.css
- express/blocks/playlist/playlist.js
- test/blocks/playlist/mocks/body.html
- test/blocks/playlist/playlist.test.js
Resolves: [MWPW-143384](https://jira.corp.adobe.com/browse/MWPW-143384)
Test URLs:
- Pre Migration Link: https://adobe.com/express/learn/express-your-brand
- Before: https://main--express-milo--adobecom.hlx.page/express/learn/express-your-brand
- After: https://MWPW-143384--express-milo--adobecom.hlx.page/express/learn/express-your-brand
- https://MWPW-143384--express-milo--adobecom.hlx.page/uk/express/learn/express-your-brand
> add playlist block

- express/blocks/page-list/page-list.css
- express/blocks/page-list/page-list.js
Resolves: [MWPW-143382](https://jira.corp.adobe.com/browse/MWPW-143382)
Test URLs:
- Pre Migration Link: https://adobe.com/express/create
- Before: https://main--express-milo--adobecom.hlx.page/express/create
- After: https://MWPW-143382--express-milo--adobecom.hlx.page/express/create
> add page-list block

- express/blocks/pricing-cards/pricing-cards.js
Sync with https://github.com/adobecom/express/pull/1214
Test URLs:
- Pre Migration Link: https://adobe.com/express/pricing
- Before: https://main--express-milo--adobecom.hlx.page/express/pricing
- After: https://marquee-tokens-sync--express-milo--adobecom.hlx.page/express/pricing
> sync with marquee-tokens for pricing-cards

- express/blocks/feature-list/feature-list.css
- express/blocks/feature-list/feature-list.js
- test/blocks/feature-list/feature-list.test.js
Resolves: [MWPW-143353](https://jira.corp.adobe.com/browse/MWPW-143353)
Test URLs:
- Pre Migration Link: https://adobe.com/express/express/create/video/music
- Before: https://main--express-milo--adobecom.hlx.page/express/express/create/video/music
- After: https://MWPW-143353--express-milo--adobecom.hlx.page/express/express/create/video/music
- https://MWPW-143353--express-milo--adobecom.hlx.page/express/create/video/montage
- https://MWPW-143353--express-milo--adobecom.hlx.page/it/express/create/video/music/collage
> add feature-list block

- express/blocks/feature-grid/feature-grid.css
- express/blocks/feature-grid/feature-grid.js
- express/blocks/pricing-cards/pricing-cards.css
- test/blocks/feature-grid/feature-grid.test.js
- test/blocks/feature-grid/mocks/body.html
Resolves: [MWPW-143352](https://jira.corp.adobe.com/browse/MWPW-143352)
Test URLs:
- After: https://MWPW-143352--express-milo--adobecom.hlx.page/express/
- https://MWPW-143352--express-milo--adobecom.hlx.page/express/solutions/blog
- https://MWPW-143352--express-milo--adobecom.hlx.page/nl/express/
> add feature-grid

- express/blocks/list/list.css
- express/blocks/list/list.js
- test/blocks/list/list.test.js
- test/blocks/list/mocks/body.html
- test/blocks/list/mocks/pricing.html
List block 
Test URLs:
- Before: https://main--express-milo--adobecom.hlx.page/express/pricing
- After: https://list-block--express-milo--adobecom.hlx.page/express/pricing
> MWPW-143375: List block

- express/blocks/how-to-steps/how-to-steps.css
- express/blocks/how-to-steps/how-to-steps.js
Resolves: [MWPW-143366](https://jira.corp.adobe.com/browse/MWPW-143366)
Test URLs:
- Before: https://main--express-milo--adobecom.hlx.page/express/discover/sizes/youtube?martech=off
- After: https://how-to-steps--express-milo--adobecom.hlx.page/express/discover/sizes/youtube?martech=off
> MWPW-143366: How to steps block migration

- express/blocks/app-banner/app-banner.css
- express/blocks/app-banner/app-banner.js
Resolves: [MWPW-143327](https://jira.corp.adobe.com/browse/MWPW-143327)
To test you'll have to test on mobile. I did a crawl and this is the only live page with the app-banner.
Test URLs:
- Before: https://main--express-milo--adobecom.hlx.page/jp/express/create/advertisement/facebook
- After: https://MWPW-143327-app-banner--express-milo--adobecom.hlx.page/jp/express/create/advertisement/facebook
> Mwpw 143327 app banner

- express/blocks/submit-email/submit-email.css
- express/blocks/submit-email/submit-email.js
Test URLs:
- Pre Migration Link: https://adobe.com/express/learn/express-your-brand?martech=off
- Before: https://main--express-milo--adobecom.hlx.page/express/learn/express-your-brand?martech=off
- After: https://MWPW-143404-submit-email--express-milo--adobecom.hlx.page/express/learn/express-your-brand?martech=off
> MWPW-143414 migrate submit email block

- express/blocks/banner/banner.css
- express/blocks/banner/banner.js
- test/blocks/banner/banner.test.js
- test/blocks/banner/mocks/cool.html
Migrate Banner cool variant from Express to Milo Express.
Resolves: [MWPW-158291](https://jira.corp.adobe.com/browse/MWPW-158291)
Test URLs:
- Before: https://banner-cool-variant-before--express-milo--adobecom.hlx.page/docs/library/kitchen-sink/banner
- After: https://banner-cool-variant-after--express-milo--adobecom.hlx.page/docs/library/kitchen-sink/banner
> [Migration] Banner cool variant

- express/blocks/content-cards/content-cards.css
- express/blocks/content-cards/content-cards.js
Port the Homepage Cards: GenAI and Discover Cards UI elements from Express to Milo
Authoring Changes Requested By Ernest: https://jira.corp.adobe.com/browse/MWPW-161344?filter=-1
Resolves: [MWPW-158262](https://jira.corp.adobe.com/browse/MWPW-158262)
Test URLs:
- After: https://homepage-cards-port--express-milo--adobecom.hlx.page/drafts/jsandlan/homepage-milo
> Homepage Cards Port

- .hlxignore
Resolves: [MWPW-161854](https://jira.corp.adobe.com/browse/MWPW-161854)
Test URLs:
- After: https://update-hlx-ignore--express-milo--adobecom.hlx.page/express/
> MWPW-161854 add hlx ignore config for top level json files

- express/blocks/cards/cards.css
aligned the text in the cards
Resolves: [MWPW-161520](https://jira.corp.adobe.com/browse/MWPW-161520)
Test URLs:
- Pre Migration Link: https://main--express--adobecom.hlx.live/drafts/nala/blocks/cards-default
- Before: https://main--express-milo--adobecom.hlx.live/drafts/nala/blocks/cards-default
- After: https://MWPW-161520--express-milo--adobecom.hlx.live/drafts/nala/blocks/cards-default
> aligned the texts properly

- express/features/direct-path-to-product/direct-path-to-product.js
- express/scripts/express-delayed.js
- express/scripts/scripts.js
- express/scripts/utils.js
Resolves: [MWPW-153686](https://jira.corp.adobe.com/browse/MWPW-153686)
Test URLs:
- After: https://mwpw-153686-pep--express-milo--adobecom.hlx.page/express/
> Mwpw 153686 pep

- express/blocks/app-banner/app-banner.js
- express/blocks/ax-columns/ax-columns.css
- express/blocks/ax-columns/ax-columns.js
- express/blocks/browse-by-category/browse-by-category.css
- express/blocks/collapsible-card/collapsible-card.js
- express/blocks/cta-carousel/cta-carousel.css
- express/blocks/discover-cards/discover-cards.css
- express/blocks/frictionless-quick-action-mobile/frictionless-quick-action-mobile.css
- express/blocks/frictionless-quick-action-mobile/frictionless-quick-action-mobile.js
- express/blocks/grid-marquee/grid-marquee.js
- express/blocks/holiday-blade/holiday-blade.css
- express/blocks/how-to-steps/how-to-steps.css
- express/blocks/how-to-steps/how-to-steps.js
- express/blocks/mobile-fork-button/mobile-fork-button.js
- express/blocks/template-x/template-x.js
- express/scripts/utils/media.js
- express/scripts/widgets/floating-cta.css
- express/scripts/widgets/floating-cta.js
Test URLs:
- After: https://sync-repos--express-milo--adobecom.hlx.page/express/
> Sync repos

- express/code/blocks/ax-columns/ax-columns.css
- express/code/blocks/blog-posts/blog-posts.css
- express/code/blocks/cta-carousel/cta-carousel.css
- express/code/blocks/feature-list/feature-list.css
- express/code/blocks/fullscreen-marquee/fullscreen-marquee.css
- express/code/blocks/gen-ai-cards/gen-ai-cards.css
- express/code/blocks/make-a-project/make-a-project.css
- express/code/blocks/pricing-cards/pricing-cards.css
- express/code/blocks/promotion/promotion.css
- express/code/blocks/steps/steps.css
- express/code/blocks/template-list/template-list.css
- express/code/blocks/template-list/template-list.js
- express/code/blocks/template-x/template-x.css
- express/code/scripts/utils.js
- express/code/styles/styles.css
Test URLs:
- After: https://style-fixes--express-milo--adobecom.hlx.page/express/
> Style fixes

- express/code/blocks/holiday-blade/holiday-blade.js
- express/code/blocks/template-x/template-rendering.js
- express/code/blocks/template-x/template-x.js
Test URLs:
- After: https://stage--express-milo--adobecom.hlx.page/express/
> fix template issue

- express/code/blocks/ax-columns/ax-columns.css
fix columns education page
Test URLs:
- Pre Migration Link: https://adobe.com/education/express/
- Before: https://main--express-milo--adobecom.hlx.page/education/express/
- After: https://general-fixes--express-milo--adobecom.hlx.page/education/express/
> fix columns education page

- express/code/blocks/susi-light/susi-light.js
Fix SUSI light modal
Resolves: [MWPW-164098](https://jira.corp.adobe.com/browse/MWPW-164098)
Test URLs:
- Pre Migration Link: https://adobe.com/education/express/
- Before: https://main--express-milo--adobecom.hlx.page/education/express/
- After: https://susi-light--express-milo--adobecom.hlx.page/education/express/
> MWPW-164098 fix susi-light

- express/code/blocks/page-list/page-list.js
Removes usage of innerHTML in the pagelist block
Resolves:  https://jira.corp.adobe.com/browse/MWPW-163924
Test URLs:
- After: https://page-list-xss--express-milo--adobecom.aem.page/docs/library/kitchen-sink/page-list
> Page List XSS Fix

- express/code/blocks/mobile-fork-button-frictionless/mobile-fork-button-frictionless.css
- express/code/blocks/mobile-fork-button-frictionless/mobile-fork-button-frictionless.js
- express/code/blocks/mobile-fork-button/mobile-fork-button.css
- express/code/blocks/mobile-fork-button/mobile-fork-button.js
**Fixes following issues|Adds following features:**
- Issue/Feature 1
- Adjusts font size and spacing for mobile fork button + mobile fork frictionless buttons for new languages. 
- Implements logic to reduce font size if the computed width of the text exceeds 70px
**Resolves:** [[MWPW-NUMBER](https://jira.corp.adobe.com/browse/MWPW-NUMBER)](https://jira.corp.adobe.com/projects/MWPW/issues/MWPW-164763)
**Steps to test the before vs. after and expectations:**
- Steps for feature 1
- Visit pages and open inspector. Set to android device and refresh. Verify text in buttons is shown fully and that the button matches the design.
https://www.figma.com/design/oEKwLBikshx4BgPmhtm7K9/Adobe.com%2Fexpress---SOT-Blocks?node-id=20272-270473&p=f&t=soVZgwzkJdOHuZHn-0
**Pages to check for regression and …
> Mfb shrink font 3

- express/code/scripts/utils/template-ckg.js
Adds basic HTML sanitization to the template-ckg file to prevent possible malicious HTML injection. Removes the < , > , \ , ', and " characters, leaves / untouched.
Resolves:  https://jira.corp.adobe.com/browse/MWPW-163930
Test URLs:
- Before: https://main--express-milo--adobecom.aem.page/express/templates
- After: https://template-ckg-xss--express-milo--adobecom.aem.page/express/templates
> DOMXSS In Template CKG

- express/code/blocks/gen-ai-cards/gen-ai-cards.js
- Added aria label to input that provides title and subtitle for better screen reader details. 
See comments from Taryn in Jira ticket. Another ticket with some visual adjustments will need to be created as a follow up.
Resolves: [MWPW-164906](https://jira.corp.adobe.com/browse/MWPW-164906)
Test URLs:
- After: https://a11y-genai-cards-accessible-name--express-milo--adobecom.hlx.page/express/experiments/ccx0199/premium-discovery-control?martech=off
**Testing notes:**
Scroll down to the section titles "Create fast with generative AI" on the provided test page.
> Adding accessible name to gen ai input

- express/code/blocks/gen-ai-cards/gen-ai-cards.css
- express/code/blocks/pricing-cards/pricing-cards.css
- express/code/blocks/toggle-bar/toggle-bar.css
- express/code/styles/styles.css
Updates the background color for the card offer container.
Resolves: 
[MWPW-164914](https://jira.corp.adobe.com/browse/MWPW-164914)
[MWPW-164901](https://jira.corp.adobe.com/browse/MWPW-164901)
Test URLs:
- Pre Migration Link: https://www.adobe.com/express/pricing
- Before: https://main--express-milo--adobecom.hlx.page/express/pricing?martech=off
- After: https://a11y-contrast-purple-savings--express-milo--adobecom.hlx.page/express/pricing?martech=off
- Before: https://main--express-milo--adobecom.hlx.page/express/fragments/toggles/recommended?martech=off
- After: https://a11y-contrast-purple-savings--express-milo--adobecom.hlx.page/express/fragments/toggles/recommended?martech=off
- Before: https://main--express-milo--adobecom.hlx.page/express/experiments/ccx0199/hp-premium-discovery-chal …
> MWPW-164914 - Accessibility contrast ratio 

- express/code/blocks/ax-columns/ax-columns.css
Fixes header overflow for the columns block fullsized variant. 
Resolves: https://jira.corp.adobe.com/browse/MWPW-166741
Test URLs:
https://ax-columns-fix--express-milo--adobecom.hlx.page/fi/express/feature/image/qr-code-generator
https://ax-columns-fix--express-milo--adobecom.hlx.page/dk/express/create/animation
https://ax-columns-fix--express-milo--adobecom.hlx.page/nl/express/create/animation
> Header Overflow Fix

- express/code/blocks/discover-cards/discover-cards.css
Removed height constraint to let content flow, and buttons can be seen in locales where content is cut off.
Resolves: [MWPW-165989](https://jira.corp.adobe.com/browse/MWPW-165989)
Test URLs:
Before: https://main--express-milo--adobecom.hlx.page/fr/express/business?martech=off
After: https://card-accessibility-fix--express-milo--adobecom.hlx.page/fr/express/business?martech=off
> [HOTFIX] Card CTA accessibility ROW bug

- express/code/blocks/discover-cards/discover-cards.css
- express/code/blocks/grid-marquee/grid-marquee.css
- express/code/blocks/simplified-pricing-cards/simplified-pricing-cards.css
- express/code/styles/styles.css
Reverts adobecom/express-milo#141
> Revert "Premium CTA Gradient"

- express/code/blocks/template-list/template-list.css
- express/code/blocks/template-list/template-list.js
- express/code/scripts/widgets/basic-carousel.css
- express/code/scripts/widgets/basic-carousel.js
Template List Updates To Align With Discover Page Redesign
Resolves: [MWPW-167002](https://jira.corp.adobe.com/browse/MWPW-167002)
Test URLs:
- After: https://template-list-updates--express-milo--adobecom.hlx.page/drafts/jsandlan/template-list-milo
> Template List Updates To Align With Discover Page Redesign

- express/code/blocks/ax-columns/ax-columns.css
- express/code/blocks/ax-columns/ax-columns.js
Resolves: [MWPW-166983](https://jira.corp.adobe.com/browse/MWPW-166983)
Test URLs:
https://ax-columns-bg-variant--express-milo--adobecom.hlx.page/drafts/jsandlan/milo-columns-bg
> Allow Background Image in AX-Columns Block

- express/code/blocks/highlight/highlight.css
- express/code/blocks/highlight/highlight.js
Resolves: [MWPW-166987](https://jira.corp.adobe.com/browse/MWPW-166987)
Test URLs:
- https://create-highlight-blade--express-milo--adobecom.hlx.page/drafts/jsandlan/milo-highlight-blade
> Create Highlight Blade

- express/code/blocks/faqv2/faqv2.css
- express/code/blocks/faqv2/faqv2.js
Update FaqV2 Block
Resolves: [MWPW-164960](https://jira.corp.adobe.com/browse/MWPW-164960)
Test URLs:
After: https://faqv2-updates--express-milo--adobecom.hlx.page/drafts/jsandlan/milo-longform-v2?martech=off
> FaqV2 Updates

- express/code/blocks/ax-columns/ax-columns.css
- express/code/blocks/ax-columns/ax-columns.js
Reverts adobecom/express-milo#172
> Revert "Allow Background Image in AX-Columns Block"

- express/code/styles/styles.css
Reverts adobecom/express-milo#176
> Revert "JP Text Content Left Aligns By Default + Authoring Ability To Center Text"

- express/code/blocks/promotion/promotion.css
Reverts adobecom/express-milo#174
> Revert "Promotions Block Changes for JP LongForm Milo"

- express/code/blocks/content-cards/content-cards.css
- express/code/blocks/content-cards/content-cards.js
* Adds ability to only author 2 cards and have those cards appear very wide.
Resolves: [MWPW-166365](https://jira.corp.adobe.com/browse/MWPW-166365)
Test URLs:
- After: https://content-cards-2-card-variant--express-milo--adobecom.hlx.page/drafts/jsandlan/milo-content-cards-two?martech=off
> Teams vs Enterprise Blade

- express/code/blocks/pricing-table/pricing-table.css
- express/code/blocks/simplified-pricing-cards/simplified-pricing-cards.css
- express/code/styles/styles.css
Reverts adobecom/express-milo#156
> Revert "Pricing Table Upgrade"

- express/code/blocks/highlight/highlight.css
- express/code/blocks/highlight/highlight.js
Resolves: [MWPW-166987](https://jira.corp.adobe.com/browse/MWPW-166987)
Test URLs:
- https://create-highlight-blade--express-milo--adobecom.hlx.page/drafts/jsandlan/milo-highlight-blade
> Create Highlight Blade 2

- express/code/styles/styles.css
* Ensure Default Content Width Aligns With Figma Across Devices
Resolves: [MWPW-167995](https://jira.corp.adobe.com/browse/MWPW-167995)
Authoring Example: [milo-discover-default-text-content.docx](https://adobe.sharepoint.com/:w:/r/sites/adobecom/Express/website/drafts/jsandlan/milo-discover-default-text-content.docx?d=wf26dae48f6fd4ba28a786c6776b85a15&csf=1&web=1&e=7Kgjx1)
Test URLs:
- After: https://milo-discover-default-content--express-milo--adobecom.aem.page/drafts/jsandlan/milo-discover-default-text-content?martech=off
> Ensure Default Content Width Aligns With Figma Across Devices

- express/code/blocks/interactive-marquee/interactive-marquee.js
Fixes the interactive marquee search button not working.
Test URLs:
- Before: https://main--express-milo--adobecom.aem.page/express/create/ai/text-effects
- After: https://im-fix--express-milo--adobecom.hlx.page/express/create/ai/text-effects
https://im-fix--express-milo--adobecom.hlx.page/express/create/ai/worksheet/flower
> Interactive Marquee Fix

- express/code/blocks/link-blade/link-blade.css
- express/code/blocks/link-blade/link-blade.js
- test/blocks/link-blade/link-blade.test.js
- test/blocks/link-blade/mocks/body.html
Adds a new link blade block.
Resolves: https://jira.corp.adobe.com/projects/MWPW/issues/MWPW-166956
Test URLs:
- After: https://link-blade--express-milo--adobecom.hlx.page/drafts/echen/link-blade
> Link blade

- express/code/blocks/content-cards/content-cards.css
* Add Black Border to CTA
Resolves: [MWPW-166365](https://jira.corp.adobe.com/browse/MWPW-166365)
Test URLs:
- Before: https://content-cards-2-card-variant--express-milo--adobecom.hlx.page/drafts/jsandlan/milo-content-cards-two?martech=off
- After: https://add-stroke-content-card-cta--express-milo--adobecom.hlx.page/drafts/jsandlan/milo-content-cards-two?martech=off
> Teams vs Enterprise Blade - Add Black Border to CTA

- express/code/blocks/ax-columns/ax-columns.css
- express/code/blocks/simplified-pricing-cards/simplified-pricing-cards.js
Test URLs:
- After: https://<branch>--express-milo--adobecom.aem.page/express/
> Mwpw 168290

- express/code/blocks/logo-row/logo-row.css
Resolves: [MWPW-168286](https://jira.corp.adobe.com/browse/MWPW-168286)
Authoring Example: [business-hub-example-logo-wall.docx](https://adobe.sharepoint.com/:w:/r/sites/adobecom/Express/website/drafts/jsandlan/business-hub-example-logo-wall.docx?d=w29727824afed42e697a13ceae443c6c6&csf=1&web=1&e=Scff8W)
Test URLs:
- Before: https://www.stage.adobe.com/express/business
- After: https://business-hub-logo-wall--express-milo--adobecom.hlx.page/drafts/jsandlan/business-hub-example-logo-wall
> Business Hub - mWeb / Desktop - Logo Wall

- express/code/blocks/ax-columns/ax-columns.css
- express/code/blocks/pricing-table/pricing-table.js
* Adds Business Hub variant for ax-columns block
* Handle header size on mobile / desktop
* Handle spacing / padding on mobile / desktop
**Authoring Example**: 
mWeb:
Resolves: [MWPW-168274](https://jira.corp.adobe.com/browse/MWPW-168274)
Desktop: 
Resolves: [MWPW-168258](https://jira.corp.adobe.com/browse/MWPW-168258)
Test URLs:
- Before: https://www.stage.adobe.com/express/business
- After: https://business-hub-success-kpis--express-milo--adobecom.aem.page/drafts/jsandlan/business-hub-success-kpis
> Business Hub - mWeb / Desktop - Success KPIs

- express/code/blocks/banner/banner.css
* Update Fonts For Banner H2 Headers
Resolves: [MWPW-168293](https://jira.corp.adobe.com/browse/MWPW-168293)
Test URLs:
- Before: https://www.stage.adobe.com/express/business
- After: https://MWPW-168293--express-milo--adobecom.aem.page/drafts/jsandlan/business-hub-example
> Business Hub - mWeb - Banner Blade

- express/code/blocks/template-x/template-rendering.js
- express/code/blocks/template-x/template-x.css
Fix for item 2 & 8 on https://jira.corp.adobe.com/browse/MWPW-168113
-hide share icon
-update button label
Test URLs:
Before: https://main--express-milo--adobecom.aem.page/express/create/logo/t-shirt?mep=%2Fexpress%2Fexperiments%2Faexg5181%2Faexg5181-replace.json--target-var1&mepButton=off&martech=off
After: https://print-update-qa-fix--express-milo--adobecom.aem.page/express/create/logo/t-shirt?mep=%2Fexpress%2Fexperiments%2Faexg5181%2Faexg5181-replace.json--target-var1&mepButton=off&martech=off
> Print qa fixes

- express/code/blocks/faqv2/faqv2.css
- express/code/blocks/faqv2/faqv2.js
* Ensures FAQV2 / FAQV2-Bold Variant Aligns Widths Across Devices
Resolves: [MWPW-163526](https://jira.corp.adobe.com/browse/MWPW-163526)
Test URLs:
- After:  https://milo-faqv2-width--express-milo--adobecom.hlx.page/drafts/jsandlan/milo-faq-discover-blocks?martech=off
> PR To Ensure FAQV2 / FAQV2-Bold Variant Aligns Widths Across Devices

- express/code/blocks/frictionless-quick-action/frictionless-quick-action.js
Reverts adobecom/express-milo#236
> Revert "[MWPW-167750] Full Editor For Remove Background"

- express/code/blocks/frictionless-quick-action/frictionless-quick-action.js
- express/code/scripts/instrument.js
Adds analytics event parameter to frictionless QA experiment. 
https://wiki.corp.adobe.com/pages/viewpage.action?spaceKey=cclight&title=Test+%7C+SEO+QA+result+in+product
`Hi Subhadeep, as per our discussion, because we are passing the parameter in the url which is supposed to be sticky across events is why I have raised this request. Because it is impossible to check if all events have that property now.
For control, I had assumed because we were able to do it for ESDK. we would also be doing it for control but that's not a blocker.
But the main issue is that were supposed to pass the sdk variants property on the [a.com](http://a.com/) pagelaod itself right? And make the property sticky across events after that. We need to look at the funnel from …
> Add Analytics To Frictionless QA Experiment

- express/code/blocks/floating-panel/floating-panel.css
- express/code/blocks/floating-panel/floating-panel.js
- express/code/blocks/susi-light/susi-light.css
- test/blocks/floating-panel/floating-panel.test.js
Resolves some quick designer comments. This won't cause any regression as it's about a new block variant.
Resolves: https://jira.corp.adobe.com/browse/MWPW-167121
Test URLs:
- Before: https://susi-light--express-milo--adobecom.aem.live/drafts/jinglhua/login-page?martech=off
- After: https://stage--express-milo--adobecom.aem.live/drafts/jinglhua/login-page?martech=off
> Make floating-panel closeable

- express/code/blocks/content-toggle/content-toggle.js
* prevents content-toggle from changing which button is highlighted when page is resized or user scrolls down the page
* this prevents a mismatched state where attempting to toggle back and forth between the content-toggle options stops working as expected
Resolves: [MWPW-170101](https://jira.corp.adobe.com/browse/MWPW-170101)
Test URLs:
- Pre Migration Link: https://adobe.com/express/business
- Before: https://main--express-milo--adobecom.aem.page/express/business
- After: https://milo-toggle-business-hub--express-milo--adobecom.hlx.page/drafts/jsandlan/milo-business-content-toggle
> [Bug] B2B Hub - Toggle Not Working Properly

- express/code/blocks/template-x/template-x.js
- express/code/scripts/utils/load-carousel.js
- express/code/scripts/widgets/basic-carousel.css
- express/code/scripts/widgets/basic-carousel.js
* enables a grid variant of the basic carousel on mobile
Resolves: [MWPW-170342](https://jira.corp.adobe.com/browse/MWPW-170342)
Authoring Example: [milo-basic-carousel-grid.docx](https://adobe.sharepoint.com/:w:/r/sites/adobecom/Express/website/drafts/jsandlan/milo-basic-carousel-grid.docx?d=w8865f58f27bd4266b1063d1ba15be1eb&csf=1&web=1&e=LjEXzP)
Test URLs:
- Pre Migration Link: Does not exist.
- Before: Does not exist.
- After: https://grid-carousel--express-milo--adobecom.aem.page/drafts/jsandlan/milo-basic-carousel-grid
> Basic Template Grid Carousel - Version 2

- express/code/blocks/content-toggle/content-toggle.js
Reverts adobecom/express-milo#269
> Revert "[Eng Enhancements] Why Choose Express Page - Default Toggle Teams first"

- express/code/blocks/content-toggle/content-toggle.js
* Ensure Content Toggle Does Not Freeze On Resize
Resolves: [MWPW-170412](https://jira.corp.adobe.com/browse/MWPW-170412)
Authoring Example: [Allow Default Content Toggle](https://adobe.sharepoint.com/:w:/r/sites/adobecom/Express/website/drafts/jsandlan/milo-allow-content-toggle.docx?d=w126dc52793024d8581e9f267dd119671&csf=1&web=1&e=IZRYMI)
Test URLs:
Pre Migration Link: https://adobe.com/express/
Before: https://main--express-milo--adobecom.aem.page/express/why-choose-express
After: https://content-toggle-fix--express-milo--adobecom.aem.page/drafts/jsandlan/milo-allow-content-toggle
> Ensure Content Toggle Does Not Freeze On Resize

- express/code/blocks/gen-ai-cards/gen-ai-cards.css
Resolves: [MWPW-170806](https://jira.corp.adobe.com/browse/MWPW-170806)
Authoring Example: [UK Campaign Gen AI Block](https://adobe.sharepoint.com/:w:/r/sites/adobecom/Express/website/uk/drafts/jsandlan/uk-campaign-gen-ai-block.doc)
Test URLs:
- Before: https://www.stage.adobe.com/uk/express/index-2?country=uk
- After: https://uk-campaign-gen-ai--express-milo--adobecom.aem.page/uk/drafts/jsandlan/uk-campaign-gen-ai-block
> [Q2 FY25 | UK LP Gen AI Block Fix

- express/code/blocks/faqv2/faqv2.css
- express/code/icons/minus-heavy.svg
- express/code/icons/plus-heavy.svg
* Align FAQv2 Expandable variant with Figma
Resolves: [MWPW-170812](https://jira.corp.adobe.com/browse/MWPW-170812)
Test URLs:
- Before: https://www.stage.adobe.com/uk/express/index-2?country=uk
- After: https://uk-campaign-faq--express-milo--adobecom.aem.page/uk/drafts/jsandlan/uk-campaign-faq
> [Q2 FY25 | UK LP Replace FAQs

- express/code/blocks/grid-marquee/grid-marquee.js
- test/blocks/grid-marquee/grid-marquee.test.js
Implements the accessibility fixes from the app-ratings block into its original block, the grid-marquee.
Resolves:  https://jira.corp.adobe.com/browse/MWPW-170565
https://jira.corp.adobe.com/browse/MWPW-170563
For the first URL:
-Using the keyboard, tab until the app store button is in focus. Open the screen reader (on Macs is command + F5) and use the voice over feature (on macs it is control + option + right arrow). Ensure that the star ratings, star image, and total ratings text elements have voiceover output. 
For the second URL:
-Ensure there is no visual regression on the page.
Test URLs:
- After: …
> [Accessibility] Grid Marquee App Ratings Accessibility Update

- express/code/blocks/cta-carousel/cta-carousel.css
- express/code/blocks/cta-carousel/cta-carousel.js
* Ensures mobile is clickable with one click
* Removes Try it text from desktop CTA and entire card is clickable in one click
* Remove blue outline from card focus state
Resolves: [MWPW-171135](https://jira.corp.adobe.com/browse/MWPW-171135)
Test URLs:
- Before: https://main--express-milo--adobecom.aem.page/uk/express/spotlight/designwithexpress/
- After: https://uk-campaign-quick-actions-cta--express-milo--adobecom.hlx.page/uk/express/spotlight/designwithexpress-cta-carousel-fix
> [Q2 FY25] | UK LP Quick Actions Block- Clickable Area

- express/code/blocks/gen-ai-cards/gen-ai-cards.css
* HIde chevrons on large screens
* Header text is centered
* Height of cards is as expected
Resolves: [MWPW-171160](https://jira.corp.adobe.com/browse/MWPW-171160)
Test URLs:
- After: https://uk-campaign-gen-ai-card-fix--express-milo--adobecom.aem.page/express/
> UI Issues For Gen-AI-Cards Block In Express Homepage

- express/code/blocks/template-x/template-x.css
- express/code/blocks/template-x/template-x.js
- express/code/scripts/template-search-api-v3.js
- express/code/scripts/widgets/masonry.js
- Adds authoring ability to specify by ID which templates show up first on load.
- Respects authoring sort options in the toolbar dropdown ui 
Resolves: [MWPW-170523](https://jira.corp.adobe.com/browse/MWPW-170523)
Test URLs:
- Before: https://main--express-milo--adobecom.aem.page/drafts/bradjohn/templates/template-tshirt?martech=off
- After: https://pdp-enhancements--express-milo--adobecom.aem.page/drafts/bradjohn/templates/template-tshirt?martech=off
> Print Enhancements

- express/code/blocks/gen-ai-cards/gen-ai-cards.css
* Add margin-left to text and gen-ai cards on desktop
Resolves: [MWPW-170806](https://jira.corp.adobe.com/browse/MWPW-170806)
Authoring Example: [uk-campaign-gen-ai-block.docx](https://adobe.sharepoint.com/:w:/r/sites/adobecom/Express/website/uk/drafts/jsandlan/uk-campaign-gen-ai-block.docx?d=w807883fdecf5482c88ce5e3d4430a3d9&csf=1&web=1&e=1qefJq)
Test URLs:
- Before: https://www.stage.adobe.com/uk/express/spotlight/designwithexpress
- After: https://uk-campaign-gen-ai-updates--express-milo--adobecom.hlx.page/uk/express/spotlight/designwithexpress
> [Q2 FY25 | UK LP Gen AI Block Fix - Margin Changes

- express/code/blocks/template-x/template-x.css
Adjust mobile card width 
Removed copy link (design asked for it to be removed on print)
Resolves: Bug commented in [MWPW-170523](https://jira.corp.adobe.com/browse/MWPW-170523)
Test URLs:
- Before: https://main--express-milo--adobecom.aem.page/drafts/bradjohn/templates/template-tshirt?martech=off
- After: https://pdp-enhancements--express-milo--adobecom.aem.page/drafts/bradjohn/templates/template-tshirt?martech=off
> MWPW-170523: Mobile card adjustment, removed copy link on print

- express/code/blocks/gen-ai-cards/gen-ai-cards.css
Reverts adobecom/express-milo#290
> Revert "[Q2 FY25 | UK LP Gen AI Block Fix - Margin Changes"

- express/code/blocks/simplified-pricing-cards/simplified-pricing-cards.css
- express/code/blocks/simplified-pricing-cards/simplified-pricing-cards.js
Fixes tooltip showing up prematurely. 
Resolves:  https://jira.corp.adobe.com/browse/MWPW-168206
Test Instructions: Go to the pricing cards and mouse around in the text content. See if the tooltip pops up before you hover over the tooltip icon.
Test URLs:
- After: https://mwpw-168206--express-milo--adobecom.aem.page/express/
> [MWPW-168206] Update simplified-pricing-cards.js

- express/code/blocks/grid-marquee/grid-marquee.css
- express/code/blocks/grid-marquee/grid-marquee.js
- express/code/blocks/simplified-pricing-cards/simplified-pricing-cards.css
- express/code/blocks/simplified-pricing-cards/simplified-pricing-cards.js
- express/code/scripts/utils.js
- express/code/styles/styles.css
- https://github.com/adobecom/express-milo/pull/299
- https://github.com/adobecom/express-milo/pull/291
- https://github.com/adobecom/express-milo/pull/303
- https://github.com/adobecom/express-milo/pull/296
Test URLs:
- Before: https://main--express-milo--adobecom.aem.live/express/?martech=off
- After: https://stage--express-milo--adobecom.aem.live/express/?martech=off
> Stage to main

- express/code/blocks/content-toggle-v2/content-toggle-v2.css
- express/code/blocks/content-toggle-v2/content-toggle-v2.js
- test/blocks/content-toggle-v2/content-toggle-v2.test.js
- test/blocks/content-toggle-v2/mocks/body.html
Implements a new block for content toggle functionality. Works the same as `content-toggle` but has a better design.
Resolves:  https://jira.corp.adobe.com/browse/MWPW-169111
https://new-tab-system--express-milo--adobecom.aem.page/docs/library/kitchen-sink/content-toggle-v2
https://new-tab-system--express-milo--adobecom.aem.page/docs/library/blocks/content-toggle-v2
Test URLs:
- After: https://new-tab-system--express-milo--adobecom.aem.page/drafts/echen/create-copy
Visit the draft page and verify that the block matches the design on mobile + desktop views, verify that the buttons change the page content accordingly. …
> [MWMW-169111] New Tab System

- express/code/blocks/ax-columns/ax-columns.css
JIRA: https://jira.corp.adobe.com/browse/MWPW-173342
Reverts adobecom/express-milo#325
> Revert "[Q2 FY25] | UK LP Update Block for Tablet"

- express/code/blocks/cta-carousel/cta-carousel.css
- express/code/blocks/discover-cards/discover-cards.js
Resolves: [MWPW-171946](https://jira.corp.adobe.com/browse/MWPW-171946)
Test URLs:
- Before: https://main--express-milo--adobecom.aem.page/express/entitled
- After: https://MWPW-171946--express-milo--adobecom.aem.page/express/entitled
> MWPW-171946: add focus back to cta and discover-cards

- express/code/scripts/utils/browse-api-controller.js
Reverting back to merge squash:  Reverts adobecom/express-milo#365
> Reverting back: "Turn off Browse API Calls on Template Search Pages""

- express/code/blocks/frictionless-quick-action/frictionless-quick-action.css
Removes the colorful text for accessibility purposes. 
---
Resolves: https://jira.corp.adobe.com/browse/MWPW-172674
---
| **After**   |  https://colorful-text-removal--express-milo--adobecom.aem.live/express/feature/image/resize |
---
---
- https://colorful-text-removal--express-milo--adobecom.aem.live/express/feature/image/resize
---
> [MWPW-172674][Sev-1] Remove Colorful Heading Text

- express/code/blocks/template-x/template-rendering.js
Resolves: [MWPW-172512](https://jira.corp.adobe.com/browse/MWPW-172512)
Test URLs:
- After: https://MWPW-172512--express-milo--adobecom.aem.page/express/
> MWPW-172512: add discerning text to link aria-label

- express/code/blocks/content-toggle/content-toggle.css
- express/code/blocks/content-toggle/content-toggle.js
Fixes the content toggle block at low resolutions. Nav buttons now stack vertically and reflow properly.
Resolves: https://jira.corp.adobe.com/browse/MWPW-172869
Zoom to 200% and try using the nav bar. Verify that you can focus the different elements to bring them to the center of the screen and that they change the section content accordingly.
Test URLs:
- After: https://content-toggle-v1-fix--express-milo--adobecom.aem.page/de/education/express/
> [MWPW-172869][Sev-1] Content Toggle Low Res Fix

- express/code/blocks/ax-columns/ax-columns.js
- express/code/blocks/content-toggle/content-toggle.css
- express/code/blocks/content-toggle/content-toggle.js
- express/code/blocks/discover-cards/discover-cards.js
- express/code/blocks/frictionless-quick-action-mobile/frictionless-quick-action-mobile.js
- express/code/blocks/frictionless-quick-action/frictionless-quick-action.css
- express/code/blocks/frictionless-quick-action/frictionless-quick-action.js
- express/code/blocks/pricing-table/pricing-table.css
- express/code/blocks/pricing-table/pricing-table.js
- express/code/blocks/template-x/template-rendering.js
- express/code/blocks/template-x/template-x.css
- express/code/scripts/utils/ax-video-controls.js
- express/code/scripts/utils/media.js
- express/code/scripts/widgets/floating-cta.css
- express/code/styles/styles.css
Stage to main for 25-22
---
- https://github.com/adobecom/express-milo/pull/342
- https://github.com/adobecom/express-milo/pull/346
- https://github.com/adobecom/express-milo/pull/348
- https://github.com/adobecom/express-milo/pull/357
- https://github.com/adobecom/express-milo/pull/362
- https://github.com/adobecom/express-milo/pull/363
- https://github.com/adobecom/express-milo/pull/369
- https://github.com/adobecom/express-milo/pull/373
- https://github.com/adobecom/express-milo/pull/375
- https://github.com/adobecom/express-milo/pull/379
- https://github.com/adobecom/express-milo/pull/371
---
| **After**   | https://stage--express-milo--adobecom.aem.page/express/?martech …
> Stage to main: RC 25-22

- .github/workflows/helpers.js
> Modified helper to not rely on local .evn credentials

- .github/workflows/merge-to-stage.yaml
Ensuring node is setup for octokit/rest to run properly. Zero impact PR
> merge to stage mod

- .github/workflows/helpers.js
- .github/workflows/merge-to-stage.yaml
pushing config to main - zero impact PR
> merge to stage mod 

- express/code/blocks/how-to-v2/how-to-v2.css
- express/code/blocks/how-to-v2/how-to-v2.js
* Gradient background appears correctly on desktop behind the thumbnail image
* Hover state appears only during interaction and disappears on mouseout
* Tablet and mobile layouts are visually unchanged and fully responsive
* li elements in the How-To block include a correctly implemented aria-labelledby attribute that references the corresponding h3 title
* No regressions to existing behavior or spacing across breakpoints
Resolves: [MWPW-172377](https://jira.corp.adobe.com/browse/MWPW-172377)
Test URLs:
- Before: https://main--express-milo--adobecom.aem.page/drafts/jsandlan/milo-how-to-v2
- After: https://milo-how-to-qa--express-milo--adobecom.aem.page/drafts/jsandlan/milo-how-to-v2
> [Design QA] How-To Block

- express/code/blocks/browse-by-category/browse-by-category.js
- express/code/blocks/template-x/template-x.js
Adds a descriptive aria label to the view all link of template-x blocks.
---
Resolves: https://jira.corp.adobe.com/browse/MWPW-173486
---
| **After**   | https://template-x-view-all-aria--express-milo--adobecom.hlx.page/in/express/collections/birthday
---
- Use the view all link feature in the template-x block. It should load and continue to work normally, but with the added bonus of a more descriptive screen reader output.
--- …
> [MWPW-173486] Purpose of link is not clear in context - view all

- express/code/blocks/highlight/highlight.css
* Updates spacing for this block
---
Resolves: [MWPW-172710](https://jira.corp.adobe.com/browse/MWPW-172710)
---
| **Before**  | https://stage--express-milo--adobecom.aem.page/drafts/jsandlan/milo-highlight-blade |
| **After**   | https://vp-ff--express-milo--adobecom.aem.page/drafts/jsandlan/milo-highlight-blade/?martech=off |
---
---
Not used anywhere in prod.
---
> [Design QA] Value Prop Blade

- express/code/scripts/instrument.js
See slack thread
---
Resolves: https://jira.corp.adobe.com/browse/MWPW-174996
---
| **Before**  | https://stage--express-milo--adobecom.aem.live/express/?martech=off |
| **After**   | https://instrument-updates--express-milo--adobecom.aem.live/express/?martech=off |
---
- In slack thread
---
No regression and tangible visitor impacts.
> [MWPW-174996] Update Instrumentation

- express/code/blocks/content-toggle/content-toggle.css
- express/code/blocks/content-toggle/content-toggle.js
Reverts adobecom/express-milo#348
https://jira.corp.adobe.com/browse/MWPW-174622
Test URLs.
[revert-348-content-toggle-v1-fix](http://revert-348-content-toggle-v1-fix--express-milo--adobecom.hlx.page/express/business)
Test Instructions.
The content toggle component at the top should look like this on mobile resolutions.
> Revert "[MWPW-172869][Sev-1] Content Toggle Low Res Fix"

- express/code/blocks/grid-marquee/grid-marquee.css
- express/code/blocks/grid-marquee/grid-marquee.js
- express/code/blocks/mobile-fork-button/mobile-fork-button.css
- express/code/blocks/mobile-fork-button/mobile-fork-button.js
- test/blocks/grid-marquee/grid-marquee.test.js
- test/blocks/mobile-fork-button/mobile-fork-button.test.js
Adds additional functionality as per test winner. See verification steps.
---
Resolves: https://jira.corp.adobe.com/browse/MWPW-173964
---
| **Before**  | https://main--express-milo--adobecom.aem.page/express/drafts/mepdev/fragments/2025/q2/mobile-fork-button/rtp-page |
| **After**   | https://mobile-fork-rtp--express-milo--adobecom.aem.page/express/drafts/mepdev/fragments/2025/q2/mobile-fork-button/rtp-page |
| **Psi**   | https://mobile-fork-rtp--express-milo--adobecom.aem.page/express/?martech=off |
---
Test in a mobile view. 
Verify functionality against [Figma Design Flow](https://www.figma.com/design/NCbUmKSe6b7T3XengqD2xE/mWeb-for-Express-Homepage---CCEX-169524?node-id=166-34635&p=f&t=3kmwl1o53MNiyBfd-0). Updates chevrons for …
> MWPW-173964 - AEXG5198 | RTP | (mWeb) Homepage

- express/code/blocks/ax-columns/ax-columns.js
- express/code/blocks/discover-cards/discover-cards.css
- express/code/blocks/gen-ai-cards/gen-ai-cards.css
- express/code/blocks/gen-ai-cards/gen-ai-cards.js
- express/code/blocks/grid-marquee/grid-marquee.css
- express/code/blocks/grid-marquee/grid-marquee.js
- express/code/blocks/hover-cards/hover-cards.css
- express/code/blocks/mobile-fork-button/mobile-fork-button.css
- express/code/blocks/mobile-fork-button/mobile-fork-button.js
- express/code/blocks/template-x-carousel-toolbar/template-x-carousel-toolbar.js
- express/code/styles/styles.css
- test/blocks/grid-marquee/grid-marquee.test.js
- test/blocks/mobile-fork-button/mobile-fork-button.test.js
- https://github.com/adobecom/express-milo/pull/377
- https://github.com/adobecom/express-milo/pull/428
- https://github.com/adobecom/express-milo/pull/419
- https://github.com/adobecom/express-milo/pull/432
- https://github.com/adobecom/express-milo/pull/429
| **Before**  | https://main--express-milo--adobecom.aem.live/express/ |
| **After**   | https://stage--express-milo--adobecom.aem.live/express/?martech=off |
> [Release] Stage to Main

- express/code/blocks/susi-light/susi-light.css
- express/code/blocks/susi-light/susi-light.js
- express/code/scripts/express-delayed.js
- test/blocks/susi-light/mocks/body.html
- test/blocks/susi-light/susi-light.test.js
Added a new b2b variant to susi-light. It has extra 2 variants: email-first, email-only.
---
Resolves: https://jira.corp.adobe.com/browse/MWPW-173410
---
| **Before**  | https://main--express-milo--adobecom.aem.page/drafts/jingle/susi-b2b?martech=off&env=prod#susi-b2b-email-first |
| **After**   | https://susi-light--express-milo--adobecom.aem.page/drafts/jingle/susi-b2b?martech=off&env=prod#susi-b2b-email-first |
---
- Open in a new incognito window
- This is a new experience. Figma is included in the ticket.
https://susi-light--express-milo--adobecom.aem.page/docs/library/kitchen-sink/susi-light?martech=off
---
All other variants should not be affected:
- (edu) )https://susi-light--express-milo--adobecom.aem.page/education/express/?martech=off# …
> [MWPW-173410] B2B SUSI-Light

- express/code/blocks/discover-cards/discover-cards.css
- express/code/blocks/discover-cards/discover-cards.js
* Updating spacing across surfaces per Figma
* prevent carousel nav from being cut off on different screen sizes
* align header font-size across surfaces
* allow authors to set any header and ensure style remains consistent
---
Resolves: [MWPW-174984](https://jira.corp.adobe.com/browse/MWPW-174984)
---
| **Before**  | https://main--express-milo--adobecom.aem.page/express/learn/students |
| **After**   | https://discover-cards-headers--express-milo--adobecom.aem.page/drafts/jsandlan/milo-discover-more-cards |
---
---
List any areas or URLs that could be affected …
> [Enhancement: Fast Follow] Discover More Cards

- express/code/blocks/ax-columns/ax-columns.css
- express/code/blocks/ax-columns/ax-columns.js
* Allow authors to set the mobile marquee image visible on tablet and mobile
---
Resolves: [MWPW-175304](https://jira.corp.adobe.com/browse/MWPW-175304)
---
| **Before**  | https://www.stage.adobe.com/express/create/brochure/tri-fold-new |
| **After**   | https://marquee-author-mobile-image--express-milo--adobecom.aem.page/drafts/jsandlan/milo-columns-bg |
**Desktop**
**Mobile**
---
---
---
> [Enhancement: Fast Follow] Authored Mobile Marquee Image

- express/code/blocks/quotes/quotes.css
- express/code/blocks/quotes/quotes.js
- express/code/scripts/widgets/basic-carousel.css
- express/code/scripts/widgets/basic-carousel.js
* Aligns spacing and styles with Figma
---
Resolves: [MWPW-172676](https://jira.corp.adobe.com/browse/MWPW-172676)
---
| **Before**  | https://stage--express-milo--adobecom.aem.page/uk/drafts/jsandlan/uk-campaign-ratings |
| **After**   | https://quotes-block-create--express-milo--adobecom.aem.page/uk/drafts/jsandlan/uk-campaign-ratings |
---
---
N/A
---
> [Design QA] Ratings & Reviews Block

- express/code/blocks/wayfinder/README.md
- express/code/blocks/wayfinder/wayfinder.css
- express/code/blocks/wayfinder/wayfinder.js
- Adds custom gradient override support 
- Layout tweaks to match Figma 
---
Resolves: [MWPW-175164](https://jira.corp.adobe.com/browse/MWPW-175164)
---
| **Before**  | https://main--express-milo--adobecom.aem.page/drafts/bradjohn/wayfinder-test |
| **After**   | https://banner-bg--express-milo--adobecom.aem.page/drafts/bradjohn/wayfinder-test?martech=off
---
> Wayfinder background

- express/code/blocks/frictionless-quick-action-mobile/frictionless-quick-action-mobile.css
- express/code/blocks/frictionless-quick-action-mobile/frictionless-quick-action-mobile.js
- express/code/blocks/frictionless-quick-action/frictionless-quick-action.css
- express/code/blocks/frictionless-quick-action/frictionless-quick-action.js
- express/code/scripts/utils/frictionless-utils.js
Reverts adobecom/express-milo#467
> Revert "Revert "[CCEX-204911] JDI | Frictionless Video QA (Phase 1: Embed)""

- express/code/scripts/utils/template-ckg.js
Fixes a HTML parsing issue causing apostrophes to be encoded incorrectly. 
---
Resolves:  https://jira.corp.adobe.com/browse/MWPW-170573
---
| **After**   | https://MWPW-170573-leaky-regex--express-milo--adobecom.aem.page/it/express/templates/invoice |
---
- Navigate down to the SEO nav section and verify that all the text in the pills looks normal. Ensure that it does not look like the bugged text in the screenshot
---
---
(If …
> [MWPW-170573] Leaky Regex Fix

- .github/workflows/helpers.js
Changing from UTC -> PST in automation workflow for better accuracy on our team's schedule.
> [Chore] UTC -> PST

- express/code/templates/blog/blog.js
Fixes blog pages potentially not rendering, as on Firefox the images are never loaded
---
None, came in as a request from someone spotting the bug.
---
| Env | URL |
| **Before**  | https://main--express-milo--adobecom.aem.live/express/learn/blog/chatgpt-as-a-search-engine |
| **After**   | https://fix-page-not-resolving--express-milo--adobecom.aem.live/express/learn/blog/chatgpt-as-a-search-engine?martech=off |
---
- The "after" page should load after a maximum of 5 seconds
---
Only reproducible on firefox
> Fix certain blog templates not rendering

- nala/blocks/floating-button/floating-button.page.cjs
- nala/blocks/floating-button/floating-button.spec.cjs
- nala/blocks/floating-button/floating-button.test.cjs
Nala test automation for  floating button block.
---
Resolves: [MWPW-176295](https://jira.corp.adobe.com/browse/MWPW-176295)
---
| Env | URL |
| **After**   | https://main--express-milo--adobecom.aem.live/drafts/nala/blocks/floating-button-page |
---
---
- https://main--express-milo--adobecom.aem.live/drafts/nala/blocks/floating-button-page
---
> Floating button

- express/code/blocks/wayfinder/wayfinder.css
Added auto margin, scoped for general usage
---
Resolves: https://jira.corp.adobe.com/browse/MWPW-178131
---
| Env | URL |
| **Before**  | https://main--express-milo--adobecom.aem.page/uk/express/learn/blog/what-to-write-for-a-baby-shower-card?martech=off|
| **After**   | https://MWPW-178131-get-started--express-milo--adobecom.aem.page/uk/express/learn/blog/what-to-write-for-a-baby-shower-card?martech=off |
---
- Open After URL
- Observe the wayfinder block is centered opposed to the before URL
---
- http://MWPW-178131-get-started---express-milo--adobecom.hlx.page/express/experiments/mep-playground/entitled-home?martech=off
---
> MWPW-178131: Wayfinder Centered

- express/code/blocks/toc-seo/toc-seo.js
- test/blocks/toc-seo/toc-seo.test.js
* Ensures table of contents appears on Safari
* PSI 95
---
Resolves: [MWPW-178764](https://jira.corp.adobe.com/browse/MWPW-178764)
---
| Env | URL |
| **Before**  | https://stage--express-milo--adobecom.aem.page/drafts/jsandlan/discover-redesign/ |
| **After**   | https://toc-node--express-milo--adobecom.hlx.page/drafts/jsandlan/discover-redesign?martech=off |
---
1. Open feature branch in Safari
2. Notice TOC fails to properly load / does not exist
---
N/A
---
> Discover - TOC Not Appearing on Safari

- .gitignore
Chore to edit .gitignore to ignore keys.
> [CHORE] Added security key prevention

- express/code/blocks/frictionless-quick-action/frictionless-quick-action.css
Reverts adobecom/express-milo#580
> Revert "adjusted max-width of the frictionless quick action button container …"

- nala/blocks/how-to-steps-carousel/how-to-steps-carousel.spec.cjs
- nala/blocks/how-to-steps-carousel/how-to-steps-carousel.test.cjs
- nala/blocks/icon-list/icon-list.page.cjs
- nala/blocks/icon-list/icon-list.spec.cjs
- nala/blocks/icon-list/icon-list.test.cjs
- Update how-to-steps-carousel to reduce number of tips.
- New icon-list block.
---
Resolves: [MWPW-180481](https://jira.corp.adobe.com/browse/MWPW-180481)
---
| Env | URL |
| **After**   | https://htsc-fix--express-milo--adobecom.aem.page/express/?martech=off |
---
---
- https://htsc-fix--express-milo--adobecom.aem.live/express/?martech=off
---
> update how-to-steps-carousel and icon-list block.

- nala/blocks/template-x-promo/template-x-promo.page.cjs
- nala/blocks/template-x-promo/template-x-promo.spec.cjs
- nala/blocks/template-x-promo/template-x-promo.test.cjs
- Fix Nala paths
Part of: https://github.com/adobecom/express-milo/pull/585
---
Resolves: [MWPW-179214](https://jira.corp.adobe.com/browse/MWPW-179214)
---
| Env | URL |
| **After**   | https://MWPW-179214--express-milo--adobecom.aem.page/express/?martech=off |
---
---
- https://MWPW-179214--express-milo--adobecom.aem.live/express/?martech=off
---
> MWPW-179214: Fix template-x-promo Nala test paths > /drafts/nala/blocks/ pattern

- fstab.yaml
- Adding the ability to bring the spreadsheets to a testing path and avoid touching Prod spreadsheets.
---
---
| Env | URL |
| **After**   | https://<branch>--express-milo--adobecom.aem.page/express/?martech=off |
---
---
---
> Add drafts folders for dev testing

- express/code/styles/styles.css
---
Resolves: https://jira.corp.adobe.com/browse/MWPW-181593
---
| Env | URL |
| **After**   | https://<branch>--express-milo--adobecom.aem.page/express/?martech=off |
---
---
---
> [Hotfix] same-fcta skiplist add simplified-pricing-cards-v2

- express/code/blocks/frictionless-quick-action/frictionless-quick-action.js
- express/code/scripts/utils/frictionless-utils.js
---
---
| Env | URL |
| **After**   | https://<branch>--express-milo--adobecom.aem.page/express/?martech=off |
---
---
---
> [CCEX-200047] Updated the remove Background quick action to use upload service

- nala/blocks/banner/banner.page.cjs
- nala/blocks/banner/banner.spec.cjs
- nala/blocks/banner/banner.test.cjs
Nala test automation for banner block, all variants.
- block contents
- button hover
- button click
---
Resolves: [MWPW-172647](https://jira.corp.adobe.com/browse/MWPW-172647)
---
| Env | URL |
| **After**   | https://banner--express-milo--adobecom.aem.page/express/?martech=off |
---
---
- https://banner--express-milo--adobecom.aem.live/express/?martech=off
---
> Nala test automation for banner block.
