adobecom/express-milo

- express/styles/styles.css
remove unnecessary style since milo is setting it already. 
This is being removed as the style was added as part of this PR to the old repo - https://github.com/adobecom/express/pull/956 
Resolves: [MWPW-142253](https://jira.corp.adobe.com/browse/MWPW-142253)
Test URLs:
- Pre Migration Link: https://adobe.com/express/feature/image/remove-background
- Before: https://main--express-milo--adobecom.hlx.page/express/feature/image/remove-background
- After: https://vhargrave-mwpw-142253-image-refactoring--express-milo--adobecom.hlx.page/express/feature/image/remove-background
> MWPW-142253 remove unnecessary style since it's being set by milo

- express/scripts/instrument.js
- express/scripts/scripts.js
- express/scripts/utils.js
fix errors that we were getting in our console
Test URLs:
- Pre Migration Link: https://adobe.com/express/feature/image/remove-background
- Before: https://main--express-milo--adobecom.hlx.page/express/feature/image/remove-background
- After: https://fix-errors--express-milo--adobecom.hlx.page/express/feature/image/remove-background
> fix errors from console

- express/blocks/banner/banner.css
- express/blocks/image-list/image-list.css
- express/blocks/steps/steps.css
- express/blocks/steps/steps.js
- express/styles/styles.css
Fix issues from sprint 4
Resolves: [MWPW-150493](https://jira.corp.adobe.com/browse/MWPW-150493)
Test URLs:
**Icons**
- Pre Migration Link: https://adobe.com/express/feature/image/remove-background
- Before: https://main--express-milo--adobecom.hlx.page/express/express/feature/image/remove-background
- After: https://MWPW-150493-fixessprint4--express-milo--adobecom.hlx.page/express/feature/image/remove-background
**Image-List**
- Before: https://main--express-milo--adobecom.hlx.page/docs/library/blocks/image-list
- After: https://MWPW-150493-fixessprint4--express-milo--adobecom.hlx.page/docs/library/blocks/image-list
**Buttons**
- Before: https://main--express-milo--adobecom.hlx.page/drafts/vhargrave/buttons
- After: https://MWPW-150493-fixessprint4--express-milo--adobecom.hlx.page/drafts/ …
> Mwpw 150493 fixessprint4

- express/blocks/ax-columns/ax-columns.css
Fix issues reported during testing. 
Resolves: [MWPW-154535](https://jira.corp.adobe.com/browse/MWPW-154535)
Test URLs:
**Padding under the columns centered wasn't quite right**
Before: https://main--express-milo--adobecom.hlx.page/express/
After: https://mwpw-154535-fixes-sprint6--express-milo--adobecom.hlx.live/kr/express/create/advertisement
**The issue that was reported here was that images on the blog pages were aligned left, but these issues were all fixed with the work on blog.** 
Before: https://main--express-milo--adobecom.hlx.page/express/learn/blog/social-media-branding-strategy
After: https://mwpw-154535-fixes-sprint6--express-milo--adobecom.hlx.page/express/learn/blog/social-media-branding-strategy
> MWPW-154535 fix padding columns

- tools/sidekick/config.json
Adding `Localize project (V2)` to sidekick tools dropdown.
Resolves: [MWPW-156695](https://jira.corp.adobe.com/browse/MWPW-156695)
Test URLs:
- After: https://rgclayton-localize-v2-option--express-milo--adobecom.hlx.page/express/
> Update config.json to include Localize v2 option

- tools/sidekick/config.json
Corrects a typo in the URL for for sidekick localization v2.
Resolves: [MWPW-156695](https://jira.corp.adobe.com/browse/MWPW-156695)
Test URLs:
- After: https://sidekick-locurl-fix--express-milo--adobecom.hlx.page/express/
> Corrects loc v2 url for sidekick

- express/blocks/icon-list/icon-list.css
- express/blocks/icon-list/icon-list.js
- test/blocks/icon-list/icon-list.test.js
- test/blocks/icon-list/mocks/4-column-body.html
- test/blocks/icon-list/mocks/body.html
Resolves: [MWPW-143368](https://jira.corp.adobe.com/browse/MWPW-143368)
Test URLs:
- Pre Migration Link: https://adobe.com/express/create/video/advertisement
- Before: https://main--express-milo--adobecom.hlx.page/express/create/video/advertisement
- After: https://MWPW-143368--express-milo--adobecom.hlx.page/express/create/video/advertisement
- https://MWPW-143368--express-milo--adobecom.hlx.page/express/nonprofits
- https://MWPW-143368--express-milo--adobecom.hlx.page/de/express/create/video/marketing
> add icon-list block

- express/scripts/utils.js
Small fixes to ensure modal works everywhere properly. 
Resolves: [MWPW-143379](https://jira.corp.adobe.com/browse/MWPW-143379)
Test URLs:
- Pre Migration Link: https://adobe.com/express/business
- Before: https://main--express-milo--adobecom.hlx.page/express/business
- After: https://MWPW-143379-modal--express-milo--adobecom.hlx.page/express/business
- After: https://MWPW-143379-modal--express-milo--adobecom.hlx.page/drafts/vhargrave/test2
> MWPW-143379 make video link selector more specific

- tools/sidekick/config.json
Adds a few more features to the sidekick that we have in the old project (Docs) and that is offered in Milo (Path)
Resolves: [MWPW-143414](https://jira.corp.adobe.com/browse/MWPW-143414)
Test URLs:
- After: https://MWPW-143414-library-config--express-milo--adobecom.hlx.page/express/
> Mwpw 143414 library config

- express/code/blocks/ax-columns/ax-columns.css
- express/code/blocks/how-to-steps-carousel/how-to-steps-carousel.css
Resolves: [MWPW-165032](https://jira.corp.adobe.com/browse/MWPW-165032)
**Before**
**After**
Test URLs:
- Pre Migration Link: https://adobe.com/de/express/create/chart/bar
- Before: https://main--express-milo--adobecom.aem.page/de/express/create/chart/bar
- After: https:// de-how-to-steps-carousel-center-issue--express-milo--adobecom.aem.page/de/express/create/chart/bar
> Mobile: How to steps carousel block not centered for DE pages.

- express/code/blocks/pricing-cards/pricing-cards.css
- express/code/blocks/pricing-cards/pricing-cards.js
- express/code/blocks/simplified-pricing-cards/simplified-pricing-cards.css
- express/code/blocks/simplified-pricing-cards/simplified-pricing-cards.js
- package.json
**Fixes following issues|Adds following features:**
- Issue/Feature 1
changed the wrapper element to button so that it is focusable
tooltip now stays open if focused via keyboard, can be dismissed by changing focus.
revamped some CSS
added missing caret at the bottom in the simplified version of the tooltip
**Resolves:**  https://jira.corp.adobe.com/browse/MWPW-160772
**Pages to check for regression and performance:**
- https://accessible-pricing-tooltip--express-milo--adobecom.hlx.page/express/
- https://accessible-pricing-tooltip--express-milo--adobecom.hlx.page/express/pricing
- https://accessible-pricing-tooltip--express-milo--adobecom.hlx.page/de/express/pricing
Visit the two pages above on the three device resolutions and press tab until the tooltip shows up. Verify that it is …
> Accessible pricing tooltip

- express/code/blocks/template-x/template-rendering.js
- Added `role="button"` to share button.
- Added `aria-label` to share button that contains the template/flyer name so the screen reader message is more descriptive than just saying "share now"
- See comments in JIra ticket for conversation with Taryn for full details.
Resolves: [MWPW-164905](https://jira.corp.adobe.com/browse/MWPW-164905)
Test URLs:
- Pre Migration Link: https://main--express--adobecom.hlx.page/in/express/fragments/homepage-desktop1
- Before: https://main--express-milo--adobecom.hlx.page/in/express/fragments/homepage-desktop1?martech=off
- After: https://a11y-templatex-share-button--express-milo--adobecom.hlx.page/in/express/fragments/homepage-desktop1?martech=off
**Testing notes:**
Scroll down to the section titled "Scroll-stopping templates" on the provided test page.
> Adding accessibility attributes to share button

- express/code/blocks/ax-marquee/ax-marquee.css
- express/code/blocks/mobile-fork-button/mobile-fork-button.css
Lowers z-index when feds nav is active, putting the mobile cta behind the curtain.
Resolves: [MWPW-166945](https://jira.corp.adobe.com/browse/MWPW-166945)
Test URLs:
- Before: https://main--express-milo--adobecom.aem.page/express/feature/image/qr-code-generator?newNav=true&martech=off
- After: https://lnav-mobile-cta--express-milo--adobecom.aem.page/express/feature/image/qr-code-generator?newNav=true&martech=off
> MWPW-166945: Lnav should take precedence

- express/code/blocks/toggle-bar/toggle-bar.css
- express/code/blocks/toggle-bar/toggle-bar.js
Fixes the toggle bar list DOM structure to to be accessiable/semantically correct.
`<ul>` and `<ol>` must only directly contain `<li>`, `<script>` or `<template>` elements
Resolves: [MWPW-164896](https://jira.corp.adobe.com/browse/MWPW-164896)
Test URLs:
- Before: https://main--express-milo--adobecom.hlx.page/express/experiments/mep-playground/entitled-home?martech=off
- After: https://a11y-toggle-bar-semantics--express-milo--adobecom.hlx.page/express/experiments/mep-playground/entitled-home?martech=off
> MWPW-164896 - Fix toggle bar to be semantic markup

- express/code/blocks/wayfinder/wayfinder.js
- Added `role=group` buttons container
- Added `aria-label `to buttons container that associates the Wayfinder text to the buttons
Screen readers should now say "Discover quick and easy... grouping Teams button".
Resolves: [MWPW-164904](https://jira.corp.adobe.com/browse/MWPW-164904)
Test URLs:
- Before: https://main--express-milo--adobecom.hlx.page/express/experiments/mep-playground/entitled-home?martech=off
- After: https://a11y-wayfinder-controls--express-milo--adobecom.hlx.page/express/experiments/mep-playground/entitled-home?martech=off
> MWPW-164904 - Wayfinder buttons not associated with text

- express/code/blocks/template-x/template-x.css
- express/code/styles/styles.css
Updating background color for the copy to clipboard tooltip to meet color contrast accessibility requirements.
Resolves: [MWPW-164899](https://jira.corp.adobe.com/browse/MWPW-164899)
Test URLs:
- Before: https://main--express-milo--adobecom.hlx.page/express/fragments/homepage-desktop?martech=off
- After: https://a11y-templatex-ctc-contrast--express-milo--adobecom.hlx.page/express/fragments/homepage-desktop?martech=off
> MWPW-164899 - Adjust color for copy to clipboard tooltip

- express/code/blocks/ax-marquee/ax-marquee.css
- express/code/blocks/ax-marquee/ax-marquee.js
- Add role='button' to container for play/pause buttons
- Toggle buttons need to use aria-pressed attribute. Add aria-pressed='false' and toggle when play/pause are pressed.
Resolves: [MWPW-164908](https://jira.corp.adobe.com/browse/MWPW-164908)
Test URLs:
- After: https://a11y-play-pause-label--express-milo--adobecom.hlx.page/express/experiments/ccx0199/premium-discovery-control?martech=off
> MWPW-164908 - Play pause label accessibility update

- express/code/blocks/pricing-cards/pricing-cards.css
- Fixes card width so content isn't cut off for devices smaller than 360px wide.
- Added a new breakpoint targeting device screens smaller than 360px wide.
Resolves: [MWPW-165757](https://jira.corp.adobe.com/browse/MWPW-165757)
**Test URLs:**
- Before: https://main--express-milo--adobecom.hlx.page/express/pricing?martech=off
- After: https://a11y-pricing-cards-cut-off--express-milo--adobecom.hlx.page/express/pricing?martech=off
> MWPW-165757 - Fix cards text getting cutt off at widths below 360px.

- express/code/styles/styles.css
Changes the default background color for hovered secondary buttons to gray-700 for better contrast.
Resolves:  https://jira.corp.adobe.com/browse/DOTCOM-129437
Test URLs:
- After: https://pricing-card-contrast-ratio--express-milo--adobecom.aem.page/express/pricing
-
> Secondary Button Contrast Ratio

- express/code/styles/styles.css
* Default left-aligns text content on JP pages
* Allows authors to use center class to center text
Resolves: [MWPW-167482](https://jira.corp.adobe.com/browse/MWPW-167482)
Test URLs:
- After: https://jp-longform-text-content--express-milo--adobecom.hlx.page/jp/drafts/milo-long-form-text-content?martech=off
> JP Text Content Left Aligns By Default + Authoring Ability To Center Text

- express/code/blocks/promotion/promotion.css
Promotions Block Changes for JP LongForm Milo:
* Ensures promotions has margin on sides for small viewports
* Adds margin bottom to ensure space between bottom of block and next element
* Reduces margin-top to bring the header closer to the block
Resolves: [MWPW-167468](https://jira.corp.adobe.com/browse/MWPW-167468)
Test URLs:
- After: https://jp-longform-promotions-mobile--express-milo--adobecom.hlx.page/drafts/jsandlan/milo-long-form-promotions?martech=off
> Promotions Block Changes for JP LongForm Milo

- express/code/styles/styles.css
**Ensure Blog Page Content Aligns With Figma** 
* Allow Left Alignment of Content
* Ensure Font Size is 20px on desktop / 16px on mobile
* Ensure Max Width set to 648px on Desktop
* Ensure space exists on either side of content on mobile viewports
Resolves: [MWPW-167568](https://jira.corp.adobe.com/browse/MWPW-167568)
Test URLs:
- After: https://milo-blog--express-milo--adobecom.hlx.page/drafts/jsandlan/milo-blog?martech=off
> Ensure Blog Page Content Aligns With Figma

- express/code/blocks/ax-marquee/ax-marquee.css
- Allow the user to move the mouse pointer over the play/pause tooltip without the tooltip disappearing.
**Context:**
Accessibility requirement:
The animation play/pause icon tooltip MUST allow the user to move the mouse pointer over without the tooltip disappearing.
Resolves: [MWPW-164903](https://jira.corp.adobe.com/browse/MWPW-164903)
Test URLs:
- After: https://a11y-play-pause-hover--express-milo--adobecom.hlx.page/express/experiments/ccx0199/premium-discovery-control?martech=off
**Testing notes:**
Mouse over the play/pause icon in the marquee. You should now beable to mouse over the tooltip (play animation) with out the tooltip disappearing.
> MWPW-164903 - Play/pause tooltip included in hover hit area

- express/code/blocks/fullscreen-marquee/fullscreen-marquee.css
Fullscreen Marquee Block Changes for JP LongForm Milo:
* Reduces desktop font-size to 45px from 80px
Resolves: [MWPW-167469](https://jira.corp.adobe.com/browse/MWPW-167469)
Test URLs:
- After: https://jp-longform-fullscreen-marquee--express-milo--adobecom.hlx.page/drafts/jsandlan/milo-long-form-fullscreen-marquee?martech=off
>  Fullscreen Marquee Block Changes for JP LongForm Milo

- express/code/blocks/cta-carousel/cta-carousel.js
Adds aria-label to the cta carousel cards so that the screen reader conveys the header of the card to the user. 
Resolves:  https://jira.corp.adobe.com/browse/MWPW-164897
Test URLs:
- After: https://cta-carousel-accessible-link--express-milo--adobecom.hlx.page/express/experiments/ccx0199/premium-discovery-control?martech=off
> CTA Carousel Cards Update

- express/code/blocks/template-x/template-rendering.js
- express/code/blocks/template-x/template-x.css
Implements an aria live region for the share arrow of our template cards.
Resolves: https://jira.corp.adobe.com/browse/MWPW-164900
Visit the template page and use the keyboard to navigate to one of the them while the screen reader is active. Use the Enter button to active the share button.
Test URLs:
- Before: https://main--express-milo--adobecom.aem.page/express/templates/?martech=off
- After: https://aria-live-template-copy--express-milo--adobecom.hlx.page/express/templates/?martech=off
> Aria live template copy

- express/code/blocks/pricing-table/pricing-table.css
- express/code/blocks/simplified-pricing-cards/simplified-pricing-cards.css
- express/code/styles/styles.css
Implements a `seamless` variant of the pricing table that matches the design for the new business hub.
Implements a `wide` variant for the simplified pricing cards to make it 400 px wide on desktop if desired by authors.
Refactors the media query cutoffs for the pricing table.
Resolves: https://jira.corp.adobe.com/projects/MWPW/issues/MWPW-166366
https://jira.corp.adobe.com/projects/MWPW/issues/MWPW-166368
Test URLs:
- Before:https://main--express-milo--adobecom.hlx.page/drafts/echen/individuals-and-teams-upgrade?martech=off
- https://main--express-milo--adobecom.hlx.page/express/pricing?martech=off
- After: https://pricing-table-upgrade--express-milo--adobecom.hlx.page/drafts/echen/individuals-and-te …
> Pricing Table Upgrade

- express/code/styles/styles.css
Default left-aligns text content on JP pages
Allows authors to use center class to center text
Resolves: [MWPW-167482](https://jira.corp.adobe.com/browse/MWPW-167482)
Test URLs:
After: https://jp-longform-text-content-2--express-milo--adobecom.hlx.page/jp/drafts/milo-long-form-text-content?martech=off
> JP Text Content Left Aligns By Default + Authoring Ability To Center Text 2

- express/code/blocks/promotion/promotion.css
Promotions Block Changes for JP LongForm Milo:
* Ensures promotions has margin on sides for small viewports
* Adds margin bottom to ensure space between bottom of block and next element
* Reduces margin-top to bring the header closer to the block
Resolves: [MWPW-167468](https://jira.corp.adobe.com/browse/MWPW-167468)
Test URLs:
After: https://jp-longform-promotions-mobile-2--express-milo--adobecom.hlx.page/drafts/jsandlan/milo-long-form-promotions?martech=off
> Promotions Block Changes for JP LongForm Milo 2

- express/code/styles/styles.css
* Ensures left and right padding exists on mobile devices for jp content text
Resolves: [MWPW-167482](https://jira.corp.adobe.com/browse/MWPW-167482)
Test URLs:
Before: https://jp-longform-text-content-2--express-milo--adobecom.hlx.page/jp/drafts/milo-long-form-text-content?martech=off
After: https://jp-content-padding--express-milo--adobecom.hlx.page/jp/drafts/milo-long-form-text-content?martech=off
> Ensure JP Content Is Padded On Mobile Devices On Left And Right

- express/code/blocks/pricing-table/pricing-table.css
- express/code/blocks/pricing-table/pricing-table.js
- express/code/blocks/simplified-pricing-cards/simplified-pricing-cards.css
Restores the pricing table wrapper CSS to ensure the table is the correct width on desktop resolutions.
Fixed issue with the bold CSS for the header not appearing. 
Implements a `seamless` variant of the pricing table that matches the design for the new business hub.
Implements a `wide` variant for the simplified pricing cards to make it 400 px wide on desktop if desired by authors.
Refactors the media query cutoffs for the pricing table.
Resolves: https://jira.corp.adobe.com/projects/MWPW/issues/MWPW-166366
https://jira.corp.adobe.com/projects/MWPW/issues/MWPW-166368
Test URLs:
- Before:https://main--express-milo--adobecom.hlx.page/drafts/echen/individuals-and-teams-upgrade?martech=off
- …
> Fix For Pricing Table Wrapper

- express/code/scripts/utils.js
As of now, when an invalid url is mis-authored for main-cta-link metadata for floatingCTA, an unhandled InvalidURL error will crash the entire page. Although this can be easily discovered fixed before publishing, it can be confusing for authors as the page hangs. This PR aims to still render out the page but log a message. A future work would be to make the authoring error more prominent and easier to understand.
Resolves: https://jira.corp.adobe.com/browse/DOTCOM-139510
Test URLs:
- Before: https://main--express-milo--adobecom.aem.page/drafts/jingle/template-x-still?martech=off
- After: https://fcta-url-try-catch--express-milo--adobecom.aem.page/drafts/jingle/template-x-still?martech=off
> [DOTCOM-139510] FloatingCTA Error Handling for Invalid Target Links

- express/code/blocks/gen-ai-cards/gen-ai-cards.css
- express/code/blocks/gen-ai-cards/gen-ai-cards.js
Changes the header tag in the gen-ai-cards carousel block from `div` to `h4`
Resolves: https://jira.corp.adobe.com/browse/MWPW-164894
Visit the after URL below and navigate to the gen ai cards section in the picture. Verify the element is an h4 in the inspector and not a div.
Test URLs:
- Before: https://main--express-milo--adobecom.hlx.page/express/experiments/ccx0167/home
- After: https://heading-accessibility-old-homepage--express-milo--adobecom.hlx.page/express/experiments/ccx0167/home
> MWPW-164894 Heading Tag Type Change

- express/code/blocks/susi-light/susi-light.js
Post migration and the adoption of UNAV, the way to detect whether a user is logged in has changed, and SUSI-Light's feature of auto redirecting logged-in users has stopped working. This PR aims to update the detection method to the latest approach and bring back the auto-redirect feature.
Resolves: https://jira.corp.adobe.com/browse/MWPW-168298
How to test:
- Connect to VPN, and visit stage.adobe.com/express/ to first sign in to stage IMS.
- Visit the test url, and make sure on top right you can see that you're signed in.
- Click the first purple "Sign up for free" CTA, and you should be redirected to the destination right away
Note: had to borrow the jarvis branch since we only have a handful of branch urls usable for testing IMS related stuff
Test URLs:
- Before: …
> [MWPW-168298] Update SUSI Signin Detection

- express/code/blocks/ax-marquee/ax-marquee.css
- express/code/blocks/ax-marquee/ax-marquee.js
- Tabbing to the play/pause button in a marquee now displays the tooltip - previously the tooltip only showed on hover.
- Pressing the Escape key after tabbing to the play/pause button will hide the tooltip. This works off of the CSS `focus-visible` pseudo selector
**Context:**
A keyboard user has to be able to see the tooltip on focus too. And then be able to escape to close the tooltip.
Resolves: [MWPW-168115](MWPW-URL)
**Test URLs:**
- After: https://a11y-keyboard-navigation-play-pause--express-milo--adobecom.hlx.page/express/experiments/ccx0199/premium-discovery-control?martech=off
**Testing notes:**
Using your keyboard, tab to the play/pause button in the marquee. …
> MWPW-168115 - Add keyboard navigation to work with play/pause tooltip

- express/code/blocks/frictionless-quick-action-mobile/frictionless-quick-action-mobile.js
- express/code/blocks/mobile-fork-button-frictionless/mobile-fork-button-frictionless.js
- express/code/blocks/mobile-fork-button/mobile-fork-button.js
As the web app product now supports all Android devices with RAM>=3GB, we start simplifying our gating logic and treating Android devices with RAM<3GB as edge cases. This allows us to lean closer to personalization setups in other a.com projects and remove express-specific customizations.
Resolves: https://jira.corp.adobe.com/browse/MWPW-167968
Test URLs:
- Before: https://main--express-milo--adobecom.aem.live/express/feature/image/flip?martech=off
- After: https://ram-check-removal--express-milo--adobecom.aem.live/express/feature/image/flip?martech=off
How to test for regression:
- Use any real Android phones or Chrome Dev Tools Emulation with Android devices, you should see the floating panel displaying 2 CTAs
- Use any real iOS phones or Chrome Dev Tools Emulation with iPhones, you …
> [MWPW-167968] Remove Android RAM check from checking Frictionless eligibility

- express/code/styles/styles.css
* Ensure both cta buttons are aligned without margin pushing one lower than the other
mWeb
Resolves: [MWPW-168285](https://jira.corp.adobe.com/browse/MWPW-168285)
Desktop
Resolves: [MWPW-168272](https://jira.corp.adobe.com/browse/MWPW-168272)
Test URLs:
- Before: https://www.stage.adobe.com/express/business
- After: https://business-hub-core-value-props--express-milo--adobecom.aem.page/drafts/jsandlan/business-hub-core-value-props
> Business Hub - dWeb / mWeb - Text Block CTA Alignment

- express/code/scripts/scripts.js
One-line change that adds a key to enable cross-site nav between our business pages and BACOM pages during Summit25. This is low-risk should have no impact on any of our pages, but will unblock authors and PdMs in planning out this feature in drafts.
Resolves: https://jira.corp.adobe.com/browse/MWPW-168746
Test URLs:
- Before: https://main--express-milo--adobecom.aem.live/express/?martech=off
- After: https://dynamic-nav-key--express-milo--adobecom.aem.live/express/?martech=off
Docs: 
https://main--milo--adobecom.hlx.page/docs/authoring/features/dynamic-navigation
https://main--milo--adobecom.hlx.page/docs/authoring/feds/global-navigation#accordion-1-trigger-18
> [MWPW-168746] Enable summit bacom dynamic nav

- express/code/blocks/template-x/template-rendering.js
Update "edit this template" button to include aria-label with template name for better accessibility . 
Screen readers will now describe "edit this template" along with the template name. 
Resolves: [MWPW-164913](https://jira.corp.adobe.com/browse/MWPW-164913)
Test URLs:
- Before: https://main--express-milo--adobecom.hlx.page/docs/authoring/template-x?martech=off
- After: https://a11y-edit-template-link--express-milo--adobecom.hlx.page/docs/authoring/template-x?martech=off
- Before: https://main--express-milo--adobecom.hlx.page/express/experiments/opt-31333/poc?martech=off
- After: https://a11y-edit-template-link--express-milo--adobecom.hlx.page/express/experiments/opt-31333/poc?martech=off
Testing notes:
Turn on screen reader. View both sample pages above. Tab to "edit this template" …
> MWPW-164913 - Edit this template button accessibility update

- express/code/blocks/link-blade/link-blade.css
Fixes an overwritten style in the new link-blade block. The text is no longer underlined when hovered over.
Resolves: https://jira.corp.adobe.com/browse/MWPW-166956
Test Instruction.
Visit before and after page, verify the link is not producing an underline when hovered over on the after page.
Test URLs:
- Before: https://stage--express-milo--adobecom.hlx.page/drafts/echen/link-blade
- After: https://link-blade-underline-fix--express-milo--adobecom.hlx.page/drafts/echen/link-blade
> Link Blade Text Decoration Fix

- express/code/scripts/scripts.js
Add `stageDomainsMap` to Express's config so that we can have auto link-mapping/replacement for authored links.
Resolves: https://jira.corp.adobe.com/browse/MWPW-168469
How to test:
On the page, click or hover onto the middle "Enter class code" CTA and notice that it's linking to the stage url of product rather than the default author prod one.
Test URLs:
- Before: https://main--express-milo--adobecom.aem.page/education/express/?martech=off
- After: https://stage-domains-map--express-milo--adobecom.aem.page/education/express/?martech=off
> [MWPW-168469] Stage domains map

- express/code/styles/styles.css
Removed selector causing link issues. 
Resolves: [MWPW-168194](https://jira.corp.adobe.com/browse/MWPW-168194)
Test URLs:
- Before: https://main--express-milo--adobecom.aem.page/express?martech=off
- After: https://link-style-adjustments--express-milo--adobecom.aem.page/express?martech=off
> Removed conflicting style

- express/code/scripts/mep/ace1057/grid-marquee/grid-marquee.css
CSS fix to fit bigger header subtitle
Resolves: [OPT-31772](https://jira.corp.adobe.com/browse/OPT-31772)
Test URLs:
- After: https://grid-marquee-toggle--express-milo--adobecom.aem.page/express/fragments/tests/2025/q1/ace1057/index-ace1057?mep=%2Fexpress%2Ffragments%2Ftests%2F2025%2Fq1%2Face1057%2Face1057.json
> [ACE1057] Grid marquee toggle CSS fix to fit bigger header subtitle

- express/code/scripts/mep/ace1057/grid-marquee/grid-marquee.js
When page is being replaced with a fragment <a> anchors are being converted to <video> tags, but the code still expects <a> tags to be present to pull video src from. 
Resolves: [OPT-31772](https://jira.corp.adobe.com/browse/OPT-31772)
Test URLs:
- Before: https:/stage--express-milo--adobecom.aem.page/express/?mep=%2Fexpress%2Ffragments%2Ftests%2F2025%2Fq1%2Face1057%2Face1057.json&audience=b2b
- After: https://grid-marquee-toggle--express-milo--adobecom.aem.page/express/?mep=%2Fexpress%2Ffragments%2Ftests%2F2025%2Fq1%2Face1057%2Face1057.json&audience=b2b
> ACE1057 : bug fix for video anchor missing when using replacePage action

- express/code/scripts/utils.js
Adds support of using page metadata to inject our dynamic commerce link logic into specified blocks.
Resolves: https://jira.corp.adobe.com/browse/MWPW-169944?filter=381833
How to test:
1. hit the branch url
2. dismiss the geo-routing modal
3. investigate the url of the first purple "Start 14-day free trial" CTA
4. it should have co=gb, compared to co=us as in stage/main
Test URLs:
- Before: https://stage--express-milo--adobecom.aem.page/uk/express/business?country=gb&martech=off
- After: https://commerce-page-metadata--express-milo--adobecom.aem.page/uk/express/business?country=gb&martech=off
> [Urgent Hotfix][MWPW-169944] Commerce Link Override by blocks specified by Page-level Metadata

- express/code/styles/styles.css
On pages that run the auto promotion, the HTML that isn't transformed via JS yet shows up on the page as seen here: 
This just hides that in styles.css, so it loads fast enough (promotion.css will come too late) 
No ticket, would take longer to write the ticket than JDI for this. 
Test URLs:
- Before: https://main--express-milo--adobecom.aem.page/express/?martech=off
- After: https://promo-hide--express-milo--adobecom.aem.page/express/?martech=off
> [JDI SPOT FIX] Hiding non loaded promotion

- express/code/blocks/floating-panel/floating-panel.css
- express/code/blocks/susi-light/susi-light.css
Moves Floating Panel to be 16px above the bottom edge compared to 100px so it covers the less important footer rather than SUSI buttons.
Resolves: https://jira.corp.adobe.com/browse/MWPW-167121
How to test:
1. Use a real phone or emulate a mobile device using Chrome
2. Visit the url
3. You should see the panel floating closer to the bottom of the page
Test URLs:
- Before: https://stage--express-milo--adobecom.aem.page/express/login?martech=off
- After: https://susi-light--express-milo--adobecom.aem.page/express/login?martech=off
> [MWPW-167121][Login Page] Lower floating panel

- express/code/scripts/scripts.js
- express/code/styles/styles.css
Adds a page metadata hero-inject-logo, that will inject express logo into the hero section (H1 but no blocks) of the page. This will be applied on https://www.adobe.com/express/ambassadors/list. The rationale behind the separation from marquee-inject-logo is to avoid impacting our blog pages, as marquee-inject-logo is on for most of our pages.
Resolves: https://jira.corp.adobe.com/browse/MWPW-170094
How to test:
- An Express logo should be visible on the feature branch link but not on stage
Test URLs:
- Before: https://stage--express-milo--adobecom.aem.page/express/ambassadors/list
- After: https://hero-logo--express-milo--adobecom.aem.page/express/ambassadors/list?martech=off
> [MWPW-170094] Hero Section logo Injection

- express/code/blocks/grid-marquee/grid-marquee.css
- express/code/blocks/grid-marquee/grid-marquee.js
Following the comments in the ticket:
- no more underlined label
- disabled scrolling on mobile and tablet when a card is up
- sticky title and X button
Resolves: https://jira.corp.adobe.com/browse/MWPW-169165
How to test:
- Use mobile setup, and click the second card on the first row
- Scroll on the background, it should be disabled now
- Scroll inside the card, the title row including the X button should be sticky now
- Use desktop setup, and hover onto the links. Labels themselves should no longer be underlined
Test URLs:
- Before: https://stage--express-milo--adobecom.aem.live/drafts/jingle/?martech=off
- After: https://grid-marquee-labels-update--express-milo--adobecom.aem.live/drafts/jingle/?martech=off
> [MWPW-169165] Grid marquee labels update for MAX

- express/code/blocks/content-toggle/content-toggle.js
* Allow authors to control whether the first or second option in the content-toggle is selected on page load
Resolves: [MWPW-170412](https://jira.corp.adobe.com/browse/MWPW-170412)
Authoring Example: [Allow Default Content Toggle](https://adobe.sharepoint.com/:w:/r/sites/adobecom/Express/website/drafts/jsandlan/milo-allow-content-toggle.docx?d=w126dc52793024d8581e9f267dd119671&csf=1&web=1&e=IZRYMI)
Authors have selected the second option and as a result on page load - the second option is selected: 
Test URLs:
- Before: https://main--express-milo--adobecom.aem.page/express/why-choose-express
- After: https://milo-allow-content-toggle--express-milo--adobecom.aem.page/drafts/jsandlan/milo-allow-content …
> [Eng Enhancements] Why Choose Express Page - Default Toggle Teams first

- express/code/blocks/content-toggle/content-toggle.js
* Prevents the right-side white highlight of the content-toggle button from extending past its right side boundary when browser window is expanded
**Before**:
**After**:
Resolves: [MWPW-170464](https://jira.corp.adobe.com/browse/MWPW-170464)
No Authoring Changes: [Allow Default Content Toggle](https://adobe.sharepoint.com/:w:/r/sites/adobecom/Express/website/drafts/jsandlan/milo-allow-content-toggle.docx?d=w126dc52793024d8581e9f267dd119671&csf=1&web=1&e=IZRYMI)
Test URLs:
- Pre Migration Link: https://adobe.com/express/business
- Before: https://main--express-milo--adobecom.aem.page/express/business
- After: https://content-toggle-resize--express-milo--adobecom.aem.page/drafts/jsandlan/milo-allow-content-toggle
> Padding Issue For Right Toggle Button When Window Resized

- express/code/blocks/how-to-v2/how-to-v2.js
* Adds a11y features outlined in document below: 
* Upon hitting "Enter/Return" a step that is closed, will open. 
* If a step is already open, hitting "Enter/Return" will NOT close that step.
* ARIA-EXPANDED: value is "false" when accordion is closed. "true" when accordion is open.
* ARIA-CONTROLS: value should be equal to the id of the content that will expand. This will indicate what content will be shown upon expand to users (in other words, what is being controlled by the button).
* ARIA-LABELLEDBY: should be the value of the id for the question button (the H3 title). This applies to all content for each accordion item.
[Annotations for the How-to Block](https://www.figma.com/design/BZFcWZY01SWY9FRXB4cIVv/Standout-Create-Page-test---CCEX-12098 …
> [Accessibility] How-To Block Enhancement

- express/code/blocks/app-ratings/app-ratings.css
- express/code/blocks/app-ratings/app-ratings.js
- express/code/blocks/grid-marquee/grid-marquee.js
- test/blocks/app-ratings/app-ratings.test.js
- test/blocks/app-ratings/mocks/body.html
Moves the app ratings feature of the grid marquee into its own separate block.
Adjusts the CSS of the app ratings slightly
Implements some accessibility + localization for new screen reader labels for app-ratings + grid marquee
Resolves: https://jira.corp.adobe.com/browse/MWPW-170516
https://jira.corp.adobe.com/browse/MWPW-170563
https://jira.corp.adobe.com/browse/MWPW-170565
Test Instructions
Open /drafts/echen/app-ratings and verify that the widget looks correct on tablet, mobile and desktop. Verify that on mobile apple devices only the apple link shows up and vice versa.
Open the inspector and check the aria labels of the app store links. Make sure they say exactly what is in the image itself. Make sure that the star icon has a role and an …
> Separate grid marquee ratings

- express/code/blocks/ax-marquee/ax-marquee.js
Adds commerce link dynamic logic to primaryCTAs under all scenarios (inline or content).
Resolves: https://jira.corp.adobe.com/browse/MWPW-170829
How to test:
- The primary "start free trial" CTA in the marquee should have co=za in the branch link, indicating that it's respecting the country=za param. This was not working on the main/stage
Test URLs:
- Before: https://stage--express-milo--adobecom.aem.page/express/spotlight/marketers?country=za&martech=off
- After: https://marquee-pricing-button-fix--express-milo--adobecom.aem.page/express/spotlight/marketers?country=za&martech=off
> [MWPW-170829][Prod Bug] Add Commerce Logic to Marquee's Primary CTAs

- express/code/blocks/ax-columns/ax-columns.css
* The H1 text size can be authored to 45px
Resolves: [MWPW-170808](https://jira.corp.adobe.com/browse/MWPW-170808)
Authoring Example: 
[uk-campaign-columns-header](https://uk-campaign-columns-header--express-milo--adobecom.aem.page/uk/drafts/jsandlan/uk-campaign-columns-header#)
**Before**:
**After**:
Test URLs:
- Before: https://www.stage.adobe.com/uk/express/index-2?country=uk
- After: https://uk-campaign-columns-header--express-milo--adobecom.aem.page/uk/drafts/jsandlan/uk-campaign-columns-header#
> [Q2 FY25 | UK LP Hero H1 size change

- express/code/blocks/grid-marquee/grid-marquee.css
- express/code/blocks/grid-marquee/grid-marquee.js
Allow headline to be decorated even when without CTAs.
Resolves: https://jira.corp.adobe.com/browse/MWPW-171267
How to test:
H1 should be bigger on the branch link now.
Test URLs:
- Before: https://stage--express-milo--adobecom.aem.page/express/fragments/tests/2025/q2/aexg5181v3/business-card?martech=off
- After: https://grid-marquee-h1-no-cta--express-milo--adobecom.aem.page/express/fragments/tests/2025/q2/aexg5181v3/business-card?martech=off
> [MWPW-171267] Decorate headline without ctas

- express/code/scripts/utils.js
Make milo variant of columns to be real milo columns.
Resolves: https://jira.corp.adobe.com/browse/MWPW-171155
How to test:
- You should see milo's columns being used on that page, vs. on branch link, you'll see Express's columns being loaded, which doesn't look as nice
Test URLs:
- Before: https://stage--express-milo--adobecom.aem.page/docs/library/kitchen-sink/?martech=off
- After: https://milo-columns--express-milo--adobecom.aem.page/docs/library/kitchen-sink/?martech=off
> Allow using Milo columns block on Express pages

- express/code/styles/styles.css
Not suppressing same-FCTA for text blocks.
Resolves: https://jira.corp.adobe.com/browse/MWPW-171491
How to test:
- Load the page in mobile
- The "Get the free plan" outline CTA should show up now. In stage it would be hidden
- There should be no any other visual changes in any other pages
Test URLs:
- Before: https://stage--express-milo--adobecom.aem.page/express/business?martech=off
- After: https://same-fcta-allow-text--express-milo--adobecom.aem.page/express/business?martech=off
> [MWPW-171491] Add Text block to the FCTA Suppression logic's AllowList

- express/code/blocks/simplified-pricing-cards/simplified-pricing-cards.css
* Remove grey background for free pricing card (1st card) across all break points
Authoring Example: [uk-campaign-columns-header.docx](https://adobe.sharepoint.com/:w:/r/sites/adobecom/Express/website/uk/drafts/jsandlan/uk-campaign-columns-header.docx?d=w37ec8326fb514e2ea8ac45a904e5db51&csf=1&web=1&e=bqDg0T)
Resolves: [MWPW-170811](https://jira.corp.adobe.com/browse/MWPW-170811)
**Authoring Changes**: 
```simplified-pricing-cards (first-card-white) ```
Test URLs:
Before: https://main--express-milo--adobecom.aem.page/uk/drafts/jsandlan/uk-campaign-columns-header?martech=off
After: https://uk-campaign-pricing-cards-outline--express-milo--adobecom.aem.page/uk/drafts/jsandlan/uk-campaign-columns-header?martech=off
> [Q2 FY25 | UK LP Pricing Card Fix

- .github/CODEOWNERS
Added CODEOWNERS files to github setups. There should be no effects on any pages.
Resolves: https://jira.corp.adobe.com/browse/MWPW-157412
Test URLs:
- Before: https://stage--express-milo--adobecom.aem.live/express/?martech=off
- After: https://codeowner--express-milo--adobecom.aem.live/express/?martech=off
> [MWPW-157412] Added CODEOWNERS

- express/code/blocks/template-list/template-list.css
- express/code/blocks/template-x/template-x.css
- express/code/blocks/template-x/template-x.js
- express/code/styles/styles.css
We have a few places where we hardcoded gnav height, which is changing soon. Update them to either use variables or a dynamic js function.
Resolves: https://jira.corp.adobe.com/browse/MWPW-171332
How to test:
- On mobile template pages, if you scroll down, the gap between the toolbar and localnav should be gone and fixed now.
- There should be no visual changes on anywhere else
- Check on both desktop and mobile for regression across pages
Test URLs:
- Before: https://stage--express-milo--adobecom.aem.live/express/templates/flyer?martech=off
- After: https://gnav-height--express-milo--adobecom.aem.live/express/templates/flyer?martech=off
> [MWPW-171332] Rm Dependency on old GNAV height

- express/code/blocks/discover-cards/discover-cards.css
* Allow 28px header on mobile
* Ensure there is distance between right side of discover cards flip variant and right side of variant
Authoring Example: [discover-cards-bugs.docx](https://adobe.sharepoint.com/:w:/r/sites/adobecom/Express/website/drafts/jsandlan/discover-cards-bugs.docx?d=w27c713e0d230492dbe00dbb032c4153f&csf=1&web=1&e=fg1s9u)
Resolves: [MWPW-171336](https://jira.corp.adobe.com/browse/MWPW-171336)
Test URLs:
- Before: https://main--express-milo--adobecom.aem.page/drafts/jsandlan/discover-cards-bugs
- After: https://discover-cards-flip-mobile-bugs--express-milo--adobecom.aem.page/drafts/jsandlan/discover-cards-bugs
> Discover Cards Flip [Mobile]: Allow 28px Headline

- express/code/blocks/pricing-cards/pricing-cards.js
- express/code/blocks/simplified-pricing-cards/simplified-pricing-cards.js
Sets tabindex to 0 for the simplified pricing card tooltip
Resolves:  https://jira.corp.adobe.com/browse/MWPW-171648
Navigate to the homepage and tab at the top of the page. The page should not jump to the pricing cards but act normally.
Navigate to the pricing card section and mouse over the area. Ensure that it behaves the same as before. 
Test URLs:
- After: https://simplified-pricing-card-tab-index--express-milo--adobecom.aem.page/express/
> [MWPW-171648] Tooltip Homepage Fix

- express/code/blocks/frictionless-quick-action-mobile/frictionless-quick-action-mobile.css
- express/code/blocks/frictionless-quick-action-mobile/frictionless-quick-action-mobile.js
- express/code/scripts/utils.js
- test/scripts/utils.test.js
Added 3 new authorable section-metadata`showwith=fqa-non-qualified`, `showwith=fqa-qualified-mobile` and `showwith=fqa-qualified-desktop` to replace `fqa-on` and `fqa-off`, but still keep it for backward compatibility for now.
Resolves: https://jira.corp.adobe.com/browse/MWPW-172485
How to test:
4 scenarios (Safari Desktop, non-Safari Desktop, Android Phone, non-Android Phone):
- Go to the branch url in each of the 4 device types
- On Safari Desktop and non-Android Phone, you should see the Columns block and no frictionless experience (ability to upload)
- On non-Safari Desktop, you should see the frictionless-quick-action block (upload dropzone)
- On Android Phone, you should see the frictionless-quick-action-mobile block (tap to upload)
Documentation: …
> [MWPW-172485] More Specific Showwith section-metadata for Frictionless Audience

- express/code/scripts/utils/pricing.js
- test/scripts/pricing.test.js
Support new segmentation commerce links to have co and lang params.
Resolves: https://jira.corp.adobe.com/browse/MWPW-172159
Test URLs:
- Before: https://stage--express-milo--adobecom.aem.page/drafts/jingle/pricing?martech=off
- After: https://commerce-segmentation--express-milo--adobecom.aem.page/drafts/jingle/pricing?martech=off
How to test:
- Go to the branch link and check the CTA in the Premium card
- It should have co and lang params
- On stage, co and lang would be undefined
Links to test for regression:
- All the pricing cards on pricing page and simplified-pricing-cards on homepage should not be affected at all, as this PR is a new feature for new authoring links.
- https://commerce-segmentation--express-milo--adobecom.aem.live/express/pricing?martech=off
- …
> [MWPW-172159] New Commerce Segmentation Links

- express/code/scripts/utils/template-ckg.js
Retire assigning of innerhtml for template-ckg.js.
Resolves: https://jira.corp.adobe.com/browse/MWPW-162405
How to test:
1. Due to ckg api does not work on branch links, the easiest way of testing is to use source override in Chrome
2. Copy the whole script file at https://github.com/adobecom/express-milo/blob/template-ckg-inner/express/code/scripts/utils/template-ckg.js, the only file modified in this PR
3. Go to www.adobe.com/express/templates/flyer and open up Dev tools, Sources tab
4. Under Overrides, check Enable Local Overrides
5. Under Page, find www.adobe.com/express/code/scripts/utils/template-ckg.js
6. Paste and override the whole file
7. Save and Refresh
8. You should see the CKG pills in search-marquee continues to work as before
9. **Once on stage, we can use …
> [MWPW-162405] Remove assigning to innerhtml

- express/code/blocks/app-ratings/app-ratings.js
- test/blocks/app-ratings/app-ratings.test.js
Allows the user to add a single customized URL to the independent `app-ratings` block.
Resolves: https://jira.corp.adobe.com/projects/MWPW/issues/MWPW-171686
Test URLs:
- After:  https://app-rating-block-enhancement--express-milo--adobecom.hlx.page/drafts/echen/app-ratings
Use the app ratings block at the bottom of the demo page above and verify it takes you to www.stage.adobe.com
> [MWPW-171686] App Ratings Block URL Customization

- express/code/blocks/ax-columns/ax-columns.css
- express/code/blocks/ax-columns/ax-columns.js
* Allow authors to set a 28px desktop header and 22px header mobile header for columns
Resolves: [MWPW-159047](https://jira.corp.adobe.com/browse/MWPW-159047)
Test URLs:
- Before: https://main--express-milo--adobecom.aem.page/drafts/jsandlan/milo-columns-header-enhancement
- After: https://milo-columns-header-enhancement--express-milo--adobecom.aem.page/drafts/jsandlan/milo-columns-header-enhancement
> Authoring Enhancement Columns Block Header Size

- express/code/blocks/gen-ai-cards/gen-ai-cards.css
Removes static height setting that was causing extra spacing in gen ai homepage cards.
Resolves:  https://jira.corp.adobe.com/browse/MWPW-172614
Test URLs:
- After: 
- https://homepage-visual-fix--express-milo--adobecom.hlx.page/uk/express/spotlight/designwithexpress
- https://homepage-visual-fix--express-milo--adobecom.hlx.page/express/ai
- https://homepage-visual-fix--express-milo--adobecom.hlx.page/express/
Test Instructions
For the first link, visit and verify the spacing is gone in the gen ai cards on desktop, mobile + tablet.
For the 2nd and third link, verify there is no visual regression on the branch vs prod.
> [MWPW-172614] Extra Spacing In Gen AI Homepage Cards

- express/code/blocks/pricing-table/pricing-table.css
- test/blocks/pricing-table/mocks/body.html
- test/blocks/pricing-table/mocks/single-section.html
- test/blocks/pricing-table/pricing-table.test.js
Restores the missing CSS rule causing table rows to not be hidden.
Resolves: [[MWPW-172777](https://jira.corp.adobe.com/browse/MWPW-172777)](https://jira.corp.adobe.com/browse/MWPW-NUMBER)
Test URLs:
- After: https://pricing-table-fix--express-milo--adobecom.aem.page/docs/library/kitchen-sink/pricing-table
https://pricing-table-fix--express-milo--adobecom.aem.page/drafts/echen/ambassadors-copy
https://pricing-table-fix--express-milo--adobecom.aem.page/express/fragments/pricing-table/enterprises-2
https://pricing-table-fix--express-milo--adobecom.aem.page/express/fragments/pricing-table/individuals-and-teams …
> [MWPW-172777] Fix For Pricing Table Collapse

- express/code/blocks/ax-columns/ax-columns.css
- express/code/blocks/frictionless-quick-action/frictionless-quick-action.css
There is a layout trash happening since the video is dynamically injected and dimensions of elements are set and then reset. We can see this more obvious on mobile view. 
* Set the approximate video dimensions for the container to reserve the space.
Resolves: [MWPW-169102](https://jira.corp.adobe.com/browse/MWPW-169102),  [MWPW-169103](https://jira.corp.adobe.com/browse/MWPW-169103),  [MWPW-169104](https://jira.corp.adobe.com/browse/MWPW-169104)
Test URLs: 
US locale:
[MWPW-169102](https://jira.corp.adobe.com/browse/MWPW-169102)
- Before: https://main--express-milo--adobecom.aem.page/express/feature/image/remove-background?martech=off
- After: https://mwpw-169103--express-milo--adobecom.aem.page/express/feature/image/remove-background?martech=off …
> MWPW-169102-169103-169104: set approximate width and height to avoid trash layout

- express/code/blocks/ax-columns/ax-columns.css
* Update layout so that on tablet the columns block displays the first column as text -> video and the next row as video -> text - similar to desktop
* Mobile remains the same with a stacked layout
Resolves: [MWPW-170814](https://jira.corp.adobe.com/browse/MWPW-170814)
**Before**:
**After**:
Test URLs:
- Before: https://main--express-milo--adobecom.aem.page/uk/drafts/jsandlan/uk-columns-tablet
- After: https://milo-uk-update-block--express-milo--adobecom.hlx.page/uk/drafts/jsandlan/uk-columns-tablet
> [Q2 FY25] | UK LP Update Block for Tablet

- express/code/features/table-of-contents-seo/table-of-contents-seo.css
- express/code/features/table-of-contents-seo/table-of-contents-seo.js
- express/code/styles/styles.css
* Ensure TOC dynamically appears as mobile TOC on mobile or desktop TOC on desktop as viewport resizes without refresh
* adds a11y fixes including skip links for mobile and desktop toc, use of semantic HTML for toc structure, aria-relevant data
Resolves: [MWPW-170230](https://jira.corp.adobe.com/browse/MWPW-170230)
**This is a sticky nav so will load below the marquee on initial load and then become sticky as the user scrolls down the page.**
Test URLs:
- After: https://toc-mobile-desktop--express-milo--adobecom.aem.page/drafts/jsandlan/milo-toc-content-numbers
> Ensure Surface Specific Table of Contents Appears Without Refresh On Correct Surface

- express/code/blocks/pricing-table/pricing-table.js
Pricing table icons (✖️  and ☑️ ) didn't have aria-labels.
* Add aria labels from placeholders or default to English
* Added properties to placeholders
Resolves: [MWPW-172779](https://jira.corp.adobe.com/browse/MWPW-172779)
Test URLs:
- Before: https://main--express-milo--adobecom.aem.page/express/pricing
- After: https://MWPW-172779--express-milo--adobecom.aem.page/express/pricing
- Placeholders: https://main--express-milo--adobecom.aem.page/express/placeholders.json
> MWPW-172779: add aria-label for check/cross icon from placeholders

- express/code/blocks/mobile-fork-button-frictionless/mobile-fork-button-frictionless.css
- express/code/blocks/mobile-fork-button-frictionless/mobile-fork-button-frictionless.js
- express/code/blocks/mobile-fork-button/mobile-fork-button.css
- express/code/blocks/mobile-fork-button/mobile-fork-button.js
- test/blocks/mobile-fork-button-frictionless/mobile-fork-button-frictionless.test.js
- test/blocks/mobile-fork-button-frictionless/mocks/body.html
- test/blocks/mobile-fork-button/mobile-fork-button.test.js
- test/blocks/mobile-fork-button/mocks/body.html
Allows the mobile fork button + frictionless version to have empty rows for `fork-cta-<x>-icon` and `fork-cta-<x>-icon-text`
https://main--express-milo--adobecom.aem.page/drafts/echen/mobile-gating-cta-blank
Resolves: https://jira.corp.adobe.com/browse/MWPW-172863
Test URLs:
- Before:
- After:  https://mobile-fork-null-column--express-milo--adobecom.hlx.page/drafts/echen/mobile-gating-cta-blank
- Control: https://mobile-fork-null-column--express-milo--adobecom.aem.page/docs/library/kitchen-sink/mobile-gating-cta
Visit the page above and change the viewport to emulate an android. Verify that the mobile fork button appears and matches the screenshot. Verify that the control link …
> Mobile fork null column

- express/code/scripts/utils/browse-api-controller.js
Browse API team wants us to reduce the number of requests coming from us, and on Search pages, the API would return empty results anyway, so adding an early termination to reduce loads.
---
Resolves: Waiting for tickets
---
| **Before**  | https://stage--express-milo--adobecom.aem.page/express/templates/search?tasks=&tasksx=&phformat=2:3&topics=happy%20cats&q=happy%20cats |
| **After**   | https://no-browse-on-search-pages--express-milo--adobecom.aem.page/express/templates/search?tasks=&tasksx=&phformat=2:3&topics=happy%20cats&q=happy%20cats?martech=off |
---
- Go to the page, open the network tab and filter by `ax-uss-api-v2`
- Reload the page
- On stage, there should be 1 call. On the dev link, there should be no such call.
---
Our dev branch …
> Turn off Browse API Calls on Template Search Pages

- express/code/blocks/template-x/template-rendering.js
Fixed issues where undefined params getting appended to Templates' CTAs.
---
Resolves: https://jira.corp.adobe.com/browse/MWPW-173736
---
| **Before**  | https://stage--express-milo--adobecom.aem.page/express/templates/flyer |
| **After**   | https://template-undefined-params--express-milo--adobecom.aem.page/express/templates/flyer?martech=off |
---
- Hover on a template, and inspect its "Edit this template" CTA
- You should see lots of undefined params in stage, but fixed in branch links
---
- https://template-undefined-params--express-milo--adobecom.aem.live/express/print?martech=off
---
There should be no visual/functional changes on any pages with templates
> [MWPW-173736] Fix undefined templates params

- express/code/blocks/cta-carousel/cta-carousel.js
This PR takes advantage of Milo's pipe operator capability that automatically adds the aria label to the button and directly constructs the view all link from the authored button.
---
Resolves: [MWPW-173484](https://jira.corp.adobe.com/browse/MWPW-173484)
---
| **After**   | https://mwpw-173484-view-all--express-milo--adobecom.aem.page/drafts/echen/cta-carousel-alt
---
- View the page and check the aria label of the view all link. Verify that it is present and that the link leads you to a sparkpost domain. 
- Some pages do not have a view all link authored. Be sure that the block does not crash in …
> [MWPW-173484] View All Button Aria

- express/code/blocks/fullscreen-marquee/fullscreen-marquee.css
Enables the free plan widget on low resolution desktops for the fullscreen marquee
---
Resolves: https://jira.corp.adobe.com/browse/MWPW-172781
---
| **After**   | https://fullscreen-marquee-free-plan--express-milo--adobecom.aem.page/express/create/poster
---
Visit the test url and either zoom in 200% or change the screen size to 320px responsive. verify that the free plan button still shows up
---
- …
> [MWPW-172781] Fullscreen Marquee Free Plan Widget Update

- express/code/blocks/frictionless-quick-action-mobile/frictionless-quick-action-mobile.css
Added max-height and object-fit contain to mobile-frictionless animation to avoid layout shifting or content overflowing.
Resolves: https://jira.corp.adobe.com/browse/MWPW-173637
Test URLs:
- Before: https://stage--express-milo--adobecom.aem.page/drafts/yge/en/feature/image/rb-mobile/ai/remove-background?martech=off
- After: https://mobile-frictionless-img-height--express-milo--adobecom.aem.page/drafts/yge/en/feature/image/rb-mobile/ai/remove-background?martech=off
How to test:
- Open the page using **Mobile Android**
- See that the image would overlap with below text in stage, but would shrink in the branch link
- All currently deployed pages should not be affected at all. This PR is to handle future content where img/video could be too tall
Page to check for regression: …
> [MWPW-173637] - Shrink Assets Too Large

- express/code/blocks/quotes/quotes.css
- express/code/blocks/quotes/quotes.js
Implements semantic HTML outputs for the quote block. Elements now use `<blockquote/>` instead of `<div/>`
Resolves: https://jira.corp.adobe.com/browse/MWPW-172622
Test URLs:
- After: https://semantic-quote-block--express-milo--adobecom.aem.page/docs/library/kitchen-sink/quotes
- https://semantic-quote-block--express-milo--adobecom.aem.page/express/create/logo
--
</body></html></div>
> Semantic quote block

- express/code/blocks/holiday-blade/holiday-blade.css
- express/code/blocks/template-x/template-x.css
Share icon was too small per accessibility.
- increase share icon size to be 24px square
Resolves: [MWPW-172189](https://jira.corp.adobe.com/browse/MWPW-172189)
Test URLs:
- Before: https://main--express-milo--adobecom.aem.page/express/feature/image/editor
- After: https://MWPW-172189--express-milo--adobecom.aem.page/express/feature/image/editor
Testing instructions: 
- visit the link
- hover over the template thumbnails
- right click and inspect the element 
- on the styles tab, activate the :hov subsection and select :focus to keep the element visible
- select the share icon svg
- width and height was changed to 16px, and overall dimensions is 24px
> MWPW-172189: enlarges icon share template X

- express/code/blocks/how-to-steps-carousel/how-to-steps-carousel.js
- Change the attribute from 'aria-role' to 'role'
- change divs to ul > li
NOTE: We are not focusing here on keyboard access, but still seems off as the arrow left and right are not compliant. Also, tab should be able to select the items as Enter does.
Resolves: [MWPW-171884](https://jira.corp.adobe.com/browse/MWPW-171884), [MWPW-171884](https://jira.corp.adobe.com/browse/MWPW-173622)
Test URLs:
- Before: https://main--express-milo--adobecom.aem.page/express/create/poster
- After: https://mwpw-171817--express-milo--adobecom.aem.page/express/create/poster
For /es locale:
https://main--express-milo--adobecom.aem.page/es/express/create/poster
> MWPW-171884-MWPW-173622: change invalid aria-role to role

- express/code/blocks/frictionless-quick-action/frictionless-quick-action.css
Adds a max 320px breakpoint for the free plan text of this block. Allows the full legal text to be shown at this low resolution.
Resolves: https://jira.corp.adobe.com/browse/MWPW-171954
https://jira.corp.adobe.com/browse/MWPW-173631
Visit the url below and open the inspector. do not emulate any devices, but shrink the responsive screen down to 320px or below. Verify that the legal text at the bottom is fully visible.
Test URLs:
- After: https://frictionless-qa-zoom--express-milo--adobecom.hlx.page/express/feature/image/remove-background
-
> [MWPW-171954][Sev-1] Frictionless QA 320px Legal Text

- express/code/blocks/discover-cards/discover-cards.js
We have set the `setsize` and `posinset` aria labels to guide the users. However, this seems unncessary while the elements are already present in the DOM. User agents can handle this. Link: https://www.w3.org/TR/wai-aria-1.2/#aria-setsize
```If all items in a set are present in the document structure, it is not necessary to set this property, as the [user agent](https://www.w3.org/TR/wai-aria-1.2/#dfn-user-agent) can automatically calculate the set size and position for each item. However, if only a portion of the set is present in the document structure at a given moment (in order to reduce document size), this property is needed to provide an explicit indication of set size.```
* remove the arial label properties for this section
---
Resolves: …
> MWPW-173643: remove unnecessary aria labels

- express/code/blocks/pricing-table/pricing-table.css
Changes the font color from gray to --var-gray-600 to meet minimum contrast requirement.
---
Resolves: https://jira.corp.adobe.com/browse/MWPW-173635
---
| **After**   | https://pricing-table-gray-contrast--express-milo--adobecom.aem.page/express/why-choose-express |
---
- Run the AX full page scan and ensure any errors that pop up are unrelated to the pricing table. There may be an issue with the red button from the experiment framework, but that is not seen by consumers.
---
List any …
> [MWPW-173635] Stronger Contrast Text For Pricing Table

- express/code/scripts/widgets/floating-cta.css
- express/code/styles/styles.css
Updates the color of the floating CTA to meet text contrast requirement
---
Resolves:  https://jira.corp.adobe.com/browse/MWPW-172612
---
| **After**   | https://floating-cta-background-update--express-milo--adobecom.aem.page/express/?martech=off |
---
Visit the homepage on mobile resolution and scroll to view the floating CTA. Ensure that the new colors meet the 4.5:1 contrast requirement. The color provided in the Figma should satisfy this requirement. …
> [MWPW-172612][Sev-1] Update Floating CTA Color

- express/code/blocks/frictionless-quick-action-mobile/frictionless-quick-action-mobile.js
Finish a TODO item and use placeholders rather than hardcoded texts to unblock international rollout.
---
Resolves: https://jira.corp.adobe.com/browse/MWPW-174225
---
| **Before**  | https://stage--express-milo--adobecom.aem.page/de/express/feature/image/remove-background-new/remove-background?martech=off |
| **After**   | https://fqa-mobile-placeholders-ctas--express-milo--adobecom.aem.page/de/express/feature/image/remove-background-new/remove-background?martech=off |
---
- Use a mobile Android device or Chrome emulator to open up the link
- Upload a photo and let the iframe load
- In stage, you should see the 2 CTAs having hardcoded English values
- In dev link, you should see the 2 CTAs having "To be translated" as that's the values in …
> [MWPW-174225][Tech Debt] Placeholders for FQA-Mobile

- express/code/scripts/template-search-api-v3.js
---
Update a header name when calling template api to address CORS error on lower envs.
Documentation: https://git.corp.adobe.com/pages/project-marvel/content-search-service/#/Search%20V3/searchContentUsingGET
---
| **Before**  | https://stage--express-milo--adobecom.aem.page/express/templates/ |
| **After**   | https://template-region-code-header--express-milo--adobecom.aem.page/express/templates/?martech=off |
---
- On stage link, template-x-block should fail to load due to CORS error
- On Dev branch link, it should load normally
---
Template-X is also used in create and color pages and many others:
- https://template-region-code-header--express-milo--adobecom.aem.live/express/colors/periwinkle?martech=off
- …
> Update template api headers

- helix-sitemap.yaml
Added x-default hreflang attribute to our sitemaps.
---
Resolves: https://jira.corp.adobe.com/browse/MWPW-173182
---
| **Before**  | https://stage--express-milo--adobecom.aem.live/express/ |
| **After**   | https://x-default-hreflang--express-milo--adobecom.aem.live/express/?martech=off |
---
- It cannot be easily verified until we deploy it to main. Once deployed, we can run the Sitemap Regenerate command and verify on https://www.adobe.com/express/sitemap.xml. If any issues were found, we can rollback right away.
- This will not have any impacts on any pages. Its impacts are limited to our sitemaps.
- We have documentations on sitemap rebuild too: https://wiki.corp.adobe.com/display/adobedotcom/Express+Sitemap+Rebuild+Documentation
---
It …
> [MWPW-173182][Sitemap] Added x-default hreflang

- express/code/blocks/faqv2/faqv2.css
- express/code/blocks/faqv2/faqv2.js
* Ensure the long form variant does not have a colored left side when expanded
* Ensure the long form variant does not have a box shadow
* Reduce the visibility of the diffuse background colors to make the effect more sublte
---
Resolves: [MWPW-172947](https://jira.corp.adobe.com/browse/MWPW-172947)
---
| **Before**  | https://main--express-milo--adobecom.aem.page/drafts/jsandlan/milo-longform-v2 |
| **After**   | https://long-form-faq-bug--express-milo--adobecom.aem.page/drafts/jsandlan/milo-longform-v2?martech=off |
---
1. Load https://long-form-faq-bug--express-milo--adobecom.aem.page/drafts/jsandlan/milo-longfo …
> [Bug] Long-Form & FAQ Blocks Not Rending Correctly on Staging

- express/code/blocks/how-to-steps-carousel/how-to-steps-carousel.css
- express/code/blocks/how-to-steps-carousel/how-to-steps-carousel.js
Updates the how to carousel to use semantic HTML + aria labels for screen readers.
Main carousel container is now a nav, tab buttons are now formal buttons.
---
Resolves: https://jira.corp.adobe.com/browse/MWPW-172050
---
| **After**   | https://how-to-carousel-states--express-milo--adobecom.hlx.page/express/create/poster |
---
Use the screen reader to navigate the how to carousel at the bottom of the page. The screen reader should tell you when you are on a selected tab. 
---
List any …
> [MWPW-172050] How To Carousel States

- express/code/blocks/template-x/template-rendering.js
- express/code/blocks/template-x/template-x.css
Per Taryn's feedback, I've made a second PR addressing the ticket.
This PR addresses an accessibility issue where the "Copied to Clipboard" status message displays with insufficient color contrast (white on white) when text spacing is applied. This specifically impacts users with limited vision or without perception of color, violating WCAG 1.4.3 Contrast (Minimum) (Level AA). The fix involves adjusting the styling of the "Copied to Clipboard" tag to ensure proper contrast and responsiveness to text length under text spacing conditions.
---
Resolves: [MWPW-172373](https://jira.corp.adobe.com/browse/MWPW-172373)
---
| **Before** | https://main--express-milo--adobecom.aem.page/express/ |
| **After** | …
> [MWPW-172373] Text Spacing Share Link V2

- express/code/blocks/fullscreen-marquee/fullscreen-marquee.css
- express/code/blocks/fullscreen-marquee/fullscreen-marquee.js
Makes the quick link button in the middle of the fullscreen marquee purely decorative. Removes the link, removes it from the tab order, sets its role to presentation so that screen readers ignore it while sighted users can still use it. Click events now pass through it to the parent link behind it.
---
Resolves: https://jira.corp.adobe.com/browse/MWPW-173725
---
| **After**   | https://MWPW-173725-remove-extra-link--express-milo--adobecom.aem.page/es/express/create/poster |
---
- Use the …
> [MWPW-173725] Hidden or empty element receives focus 

- express/code/blocks/grid-marquee/grid-marquee.js
---
Resolves: https://jira.corp.adobe.com/browse/MWPW-173640
---
| **After**   | https://MWPW-173640-dismiss-content--express-milo--adobecom.aem.page/express/ |
---
- Hover over the grid marquee cards and press Escape. The drawer should disappear.
---
- https://MWPW-173640-dismiss-content--express-milo--adobecom.aem.page/express/
---
> [MWPW-173640] Grid Marquee Additional content not dismissible

- express/code/blocks/cards/cards.js
The ask is to remove the highlight variant instead of fixing a11y issues.
- Filter out the highlight variant, if found, we remove the content, else we render the card.
---
Resolves: [MWPW-174872](https://jira.corp.adobe.com/browse/MWPW-174872)
---
| **Before**  | https://main--express-milo--adobecom.aem.page/express/create/poster |
| **After**   | https://MWPW-174872--express-milo--adobecom.aem.page/express/create/poster?martech=off |
---
- Load the page and locate the 
- What to expect **before** : the title `Looking for Adobe Express for Education?` is present with three cards showing up. and **after** the change: `Looking for Adobe Express for Education?` is not present and the cards are removed.
---
List any areas or URLs …
> MWPW-174872: removing card highlight variant

- express/code/blocks/template-x/template-rendering.js
As part of the arial label update to add context, they wanted to remove the `:` 
change`Edit this template: Grey Handwritten Wellness Logo` 
to `Edit this template Grey Handwritten Wellness Logo` 
We did some work on the PRs below, but missed this one part.
---
Resolves: [MWPW-172516](https://jira.corp.adobe.com/browse/MWPW-172516)
Related to: https://github.com/adobecom/express-milo/pull/342, https://github.com/adobecom/express-milo/pull/346
---
| **Before**  | https://main--express-milo--adobecom.aem.page/express/create/logo?martech=off  |
| **After**   | https://mwpw-172516--express-milo--adobecom.aem.page/express/create/logo?martech=off |
---
- locate the Template block
- Inspect the template image element by right clicking …
> MWPW-172516: remove : and extra line

- express/code/scripts/utils.js
Svg icons were accessible to screen readers. 
- Make SVGs icons aria-label-hidden true to hide svgs from screen readers.
---
Resolves: [MWPW-172621](https://jira.corp.adobe.com/browse/MWPW-172621)
---
| **Before**  | https://main--express-milo--adobecom.aem.page/express/feature/image/convert/jpg-to-png |
| **After**   | https://mwpw-172621--express-milo--adobecom.aem.page/express/feature/image/convert/jpg-to-png?martech=off |
---
- Load the page, and locate the How To component.
- Right click on the icons on the block.
- What to expect **before**  there was no aria-label-hidden and **after** we see the aria-label-hidden set to true.
---
- …
> MWPW-172621: set all svgs to role=presentation

- express/code/blocks/frictionless-quick-action/frictionless-quick-action.css
- express/code/blocks/frictionless-quick-action/frictionless-quick-action.js
- express/code/icons/dash-rectangle.svg
Restyles the frictionless QA dropzone to use more responsive styling so that information and visual elements are preserved at 320px and when the user uses the text spacing plugin.
Restyles the video element so that it is responsive at mobile sizes and so that the pause button is now fully in the view port at all screen sizes.
---
Resolves: https://jira.corp.adobe.com/browse/MWPW-172477
---
| **After**   |  https://mwpw-172477-frictionless-qa--express-milo--adobecom.hlx.page/express/feature/image/remove-background |
---
- What to expect …
> [MWPW-172477] Frictionless QA Text Spacing 

- express/code/blocks/how-to-v2/how-to-v2.css
* Reduce max-height of image / video across surfaces
* Prevent blurred bg image from appearing cutoff on larger surfaces
---
Resolves: [MWPW-172377](https://jira.corp.adobe.com/browse/MWPW-172377)
---
| **Before**  | https://stage--express-milo--adobecom.aem.page/drafts/jsandlan/milo-how-to-v2 |
| **After**   | https://ht-ff--express-milo--adobecom.aem.page/drafts/jsandlan/milo-how-to-v2 |
---
---
Not used in prodi.
---
> [Design QA] How-To Block - FF

- express/code/blocks/pricing-cards/pricing-cards.js
Creating a dynamic div or h2 based on the present of content (text). This is a fast follow from https://github.com/adobecom/express-milo/pull/422. 
ALSO: changed back the previous h3 to h2 look up on the legacy cards.
---
Resolves: [MWPW-173192](https://jira.corp.adobe.com/browse/MWPW-173192)
---
| **Before**  | https://main--express-milo--adobecom.aem.page/express/pricing |
| **After**   | https://MWPW-173192--express-milo--adobecom.aem.page/express/pricing?martech=off |
---
---
---
(If …
> MWPW-173192: add dynamic tag based on text content

- express/code/blocks/template-x/template-rendering.js
- express/code/blocks/template-x/template-x.css
Fix accessibility issue where share button is improperly nested inside a link element, causing screen readers to announce it incorrectly as "Share button link" instead of just "Share button". This resolves WCAG 4.1.2 Name, Role, Value compliance by ensuring interactive elements are not nested within other interactive elements.
---
Resolves: [[MWPW-171815](https://jira.corp.adobe.com/browse/MWPW-171815)](https://jira.corp.adobe.com/browse/MWPW-171815)
---
| **Before**  | https://main--express-milo--adobecom.aem.page/express/feature/image/editor |
| **After**   | https://mwpw-171815-share-label--express-milo--adobecom.aem.page/express/feature/image/editor?
|After |  https://mwpw-171815-share-label--express-milo--adobecom.aem.page/express/templates/ …
> [MWPW-171815] updated share icon wrapper to be sibling instead of child of <a>

- express/code/blocks/discover-cards/discover-cards.css
Discover-cards have .gallery styles that can pollute the global space when other blocks using .gallery or compact-carousel are authored on the same page. This PR aims to remove those without causing any visual/functional changes.
---
Resolves: https://jira.corp.adobe.com/browse/MWPW-166953
---
| **Before**  | https://stage--express-milo--adobecom.aem.page/express/create/brochure/tri-fold-new |
| **After**   | https://scoping-discover-cards-gallery--express-milo--adobecom.aem.page/express/create/brochure/tri-fold-new?martech=off |
---
- Visit the urls in stage, and you should see very large templates in template-x-carousel-toolbar block. This is caused by conflicting styles between template-x-carousel-toolbar and discover-cards.
- Visit the after …
> [MWPW-166953] Discover-Cards Gallery Style Leakage

- express/code/blocks/gen-ai-cards/gen-ai-cards.css
- express/code/scripts/utils/media.js
- express/code/styles/styles.css
We have two regressions coming from the release:
1 - Misalignment on the h2 gen-ai homepage-spotlight: Introduced here MWPW-172127. PR https://github.com/adobecom/express-milo/pull/429
2 - Play / pause button in hero-animation column variant. Originally from MWPW-171817. PR https://github.com/adobecom/express-milo/pull/379
- Revert the h3 > h2 update
- Create a container for the video element, so the video element rather the parent content
---
Resolves: [MWPW-171817](https://jira.corp.adobe.com/browse/MWPW-171817)
---
| **Before**  | https://main--express-milo--adobecom.aem.page/uk/express/spotlight/designwithexpress |
| **After**   | https://video-buttons-and-alignment-fix--express-milo--adobecom.aem.page/uk/express/spotlight/designwithexpress?m …
> MWPW-171817-MWPW-172127: Post-release fix play / pause position & heading alignment

- .github/pull_request_template.md
- express/code/blocks/ax-panels/ax-panels.css
- express/code/blocks/ax-panels/ax-panels.js
- express/code/blocks/cta-cards/cta-cards.css
- express/code/blocks/hover-cards/hover-cards.css
- express/code/blocks/template-x-carousel-toolbar/template-x-carousel-toolbar.css
Right now new blocks introduced for Get Started Blade work well together, but don't work well when authored separately. This PR is to make them more usable even when authored individually on a page, like our documentations space.
---
Resolves: https://jira.corp.adobe.com/browse/MWPW-174218
---
| **Before**  | https://stage--express-milo--adobecom.aem.live/docs/library/kitchen-sink/hover-cards |
| **After**   | https://get-started-blocks-docs--express-milo--adobecom.aem.live/docs/library/kitchen-sink/hover-cards?martech=off |
| **Before**  | https://stage--express-milo--adobecom.aem.live/docs/library/kitchen-sink/cta-cards |
| **After**   | https://get-started-blocks-docs--express-milo--adobecom.aem.live/docs/library/kitchen-sink/cta-cards?martech …
> [MWPW-174218] Get Started Blade Blocks Stand-alone Ready

- express/code/blocks/frictionless-quick-action-mobile/frictionless-quick-action-mobile.css
Related to https://github.com/adobecom/express-milo/pull/439. 
---
Related to: [MWPW-171817](https://jira.corp.adobe.com/browse/MWPW-171817)
Related to: [MWPW-172127](https://jira.corp.adobe.com/browse/MWPW-172127)
---
| **Before**  | https://main--express-milo--adobecom.aem.page/fr/express/feature/image/remove-background-new/white |
| **After**   | https://frictionless-video-overlap--express-milo--adobecom.aem.page/fr/express/feature/image/remove-backgroundnew/white?martech=off |
---
--- …
> fix mobile dropzone overlap / video

- express/code/blocks/discover-cards/discover-cards.css
* Ensures mobile carousel is able to scroll fully left and right on mobile
---
Resolves: [MWPW-175413](https://jira.corp.adobe.com/browse/MWPW-175413)
---
| **Before**  | https://stage--express-milo--adobecom.aem.page/express/create/brochure/tri-fold-new  |
| **After**   | https://discover-more-cards-mobile-bug--express-milo--adobecom.aem.page/express/create/brochure/tri-fold-new |
---
---
- https://stage--express-milo--adobecom.aem.live/express/create/brochure/tri-fold-new
---
(If applicable) Add …
> [Bug] Discover More Cards Cut-off - Mobile

- express/code/blocks/gen-ai-cards/gen-ai-cards.css
- express/code/blocks/gen-ai-cards/gen-ai-cards.js
This is a follow up for https://github.com/adobecom/express-milo/pull/429. Some were slightly directly, others were things Mariah found.
1 - Due to the content order switch the card layout change a bit, so the spacing below the image was getting dynamic spacing based on 1 or two lines. That created misalignment in titles (worse in mobile view)
- Reactor the card content: Media is separated from the text and footer. 
2 - Carousel was not adding right space when it hit the last one.
- Add padding on left-fader
3 - Spotlight card had a fix width creating a break in design.
- Set width to 100%
4 - Font size homepage heading was wrong on both desktop and mobile
- Change desktop heading to 36px and Mobile to 28px
5 - Homepage carousel container margin was off by 4 px
- Change margin to 20px
--- …
> MWPW-172127-2: refactor gen-ai card DOM for flex layout

- express/code/blocks/browse-by-category/browse-by-category.js
Enables support for H2-H4 for this browse by category block
---
Resolves:  https://jira.corp.adobe.com/browse/MWPW-173084
---
| Env | URL |
| **After**   | https://browse-by-category-h2--express-milo--adobecom.aem.page/express/templates/ |
| **After** |  https://browse-by-category-h2--express-milo--adobecom.aem.page/drafts/echen/browse-by-category|
---
- We expect the stage version to have the header and the 3 versions shown on the draft page to have headers that look alike
---
(If applicable) Add context, related PRs, or …
> Multiple Header Support For Browse By Category

- express/code/blocks/template-x-carousel-toolbar/template-x-carousel-toolbar.js
- express/code/scripts/template-utils.js
Filtered out invalid templates that could cause Template-x-carousel-toolbar rendering errors.
---
Resolves: https://jira.corp.adobe.com/browse/MWPW-176361
---
| Env | URL |
| **Before**  | https://stage--express-milo--adobecom.aem.page/drafts/yge/en/create/new-layout/poster/classroom |
| **After**   | https://template-carousel-filter-invalid--express-milo--adobecom.aem.page/drafts/yge/en/create/new-layout/poster/classroom?martech=off |
---
- Visit the url and scroll down a bit to see the blade and Templates tab
- On the stage link, the block should fail to load, as that page's particular query will trigger an invalid template.
- On the dev branch link, the block should continue to function.
--
> [MWPW-176361] Filter Invalid Templates for Template-x-carousel-toolbar

- express/code/blocks/simplified-pricing-cards/simplified-pricing-cards.css
1) Changes the width of the card from 270px to 294px on 1280px - 1440px breakpoints.
2) Updated header CSS rules to be inclusive of h3, h4, h5, and h6 elements.
**Authors seem to have added an italic to the "Contact Sales" part of the block, which should be reverted to achieve the original look*
---
Resolves: https://jira.corp.adobe.com/browse/MWPW-176717
---
| Env | URL |
| **After**   | https://pricing-card-h3--express-milo--adobecom.aem.page/express/?martech=off |
---
- Visit the page and view the pricing cards at 1281px …
> Pricing Card CSS Fix

- express/code/blocks/mobile-fork-button-dismissable/mobile-fork-button-dismissable.js
Fix mobile-fork-button-dismissable block.
---
| Env | URL |
| **Before**  | https://main--express-milo--adobecom.aem.live/express/?martech=off |
| **After**   | https://hotfix-dismiss-button--express-milo--adobecom.aem.live/express/?martech=off |
---
- Load in Android Mobile Emulator/Phone
- Dismiss the floating panel by closing it
- Scroll to bottom of the page
- On stage, you would see a weird "mobile" text floating
- On dev branch, it should be cleaned up
> [Hotfix] Remove temporary block

- express/code/styles/styles.css
Currently. page CTAs that are considered same-cta as floatingCTA would be hidden. However, this rule runs into issues when fragments and personalization are applied. This PR aims to improve the matching.
---
Resolves: https://jira.corp.adobe.com/browse/OPT-33868
---
| Env | URL |
| **Before**  | https://stage--express-milo--adobecom.aem.page/express/?mep=%2Ffragments%2Fjpratt%2Fsandbox%2Faexg5271-1.json |
| **After**   | https://fcta-block-matching--express-milo--adobecom.aem.page/express/?mep=%2Ffragments%2Fjpratt%2Fsandbox%2Faexg5271-1.json |
---
- Emulate iOS and Load the page
- Scroll down to the tabs and click Students
- On stage, there should be an unintentionally hidden CTA. On dev branch, it should be visible
---
- This PR should not affect any floating-cta …
> [OPT-33868] More accurate block matching for FloatingCTA rules

- express/code/blocks/faq/faq.js
- test/blocks/faq/faq.test.js
- test/blocks/faq/mocks/body.html
- test/blocks/faq/mocks/hide-faq-schema.html
- Add variant option to FAQ block to not inject JSON schema into the page heading. The variant to add is `hide-faq-schema`.
- Add unit tests for FAQ block.
---
Resolves: [MWPW-174671](https://jira.corp.adobe.com/browse/MWPW-174671)
---
Copy of Pricing page with 5 FAQs on the page. 4 of the 5 have the new `hide-faq-schema` variant applied.
| Env | URL | # of Schemas |
|-------------|-----|-----|
| **Before**  | https://main--express-milo--adobecom.hlx.page/drafts/yolles/pricing | 5 |
| **After**   | https://mwpw-174671-faq-schema--express-milo--adobecom.hlx.page/drafts/yolles/pricing?martech=off | 1 |
Single FAQ block with no variant or page meta data.
| Env | URL | # of Schemas |
|-------------|-----|-----|
| **Before**  | https://main--express-milo--adobecom.hlx.page/drafts/yolles/faq | …
> MWPW-174671: Make FAQ block schema optional

- express/code/blocks/ax-columns/ax-columns.css
Adds a section metadata patch style for the MAX campaign image 
---
https://jira.corp.adobe.com/browse/MWPW-177449
---
| Env | URL |
| **After**   | https://max-patch--express-milo--adobecom.aem.page/drafts/bradjohn/max-entitled-campaign?martech=off |
---
- Check that mobile has section 400 spacing above the image on mobile
---
None, fixed with section metadata to be non invasive
> [HOTFIX] MAX patch

- express/code/blocks/template-x-carousel-toolbar/template-x-carousel-toolbar.js
Fix an issue where the default sort order doesn't follow authoring.
---
Resolves: https://jira.corp.adobe.com/browse/MWPW-177665
---
| Env | URL |
| **Before**  | https://stage--express-milo--adobecom.aem.live/express/create/poster |
| **After**   | https://template-carousel-default-order--express-milo--adobecom.aem.live/express/create/poster?martech=off |
---
- Scroll down to the tabs and templates section
- On stage, it would default to "Popular". On dev branch, it would default to "New templates" following the authoring.
> [MWPW-177665][Bug] [Create Page] Template-Carousel Default Index Fix

- express/code/blocks/mobile-fork-button-dismissable/mobile-fork-button-dismissable.js
Fixes the dismissable continue button selector to work on localized geos.
---
Resolves: n/a
---
| Env | URL |
| **Before**  | https://stage--express-milo--adobecom.aem.page/fr/express/ |
| **After**   | https://dismissable-cta-hotfix--express-milo--adobecom.aem.page/fr/express/?martech=off |
---
- Load in mobile Android emulator/phone
- The continuer button should work in dev branch but not in stage
---
- https://dismissable-cta-hotfix--express-milo--adobecom.aem.live/express/?martech=off
---
> Update dismissable continue selector.

- express/code/blocks/pricing-cards-v2/pricing-cards-v2.css
- express/code/blocks/pricing-cards-v2/pricing-cards-v2.js
Updated the handlePriceToken function in the pricing-cards-v2 component to properly handle scenarios where multiple pricing tokens exist on a single page, rather than only processing the first occurrence.
**Page is currently under authoring, so this issue is not on production**
---
Resolves:  https://jira.corp.adobe.com/browse/MWPW-178688
---
| Env | URL |
| **Before**  | https://stage--express-milo--adobecom.aem.page/drafts/echen/pricing-bug-demo?tab=3 |
| **After**   | https://pricing-v3-y2p-multiple--express-milo--adobecom.aem.page/drafts/echen/pricing-bug-demo?tab=3 |
---
- Visit the link above (it should bring you to the correct pricing card tab) and …
> Support For Multiple Pricing Tokens In Pricing Cards V2

- express/code/blocks/gen-ai-cards/gen-ai-cards.js
Added url update if ?lingo exists for lingo poc.
---
| Env | URL |
| **Before**  | https://stage--express-milo--adobecom.aem.page/express/lingo/?lingo=1 |
| **After**   | https://lingo-poc-2--express-milo--adobecom.aem.page/express/lingo/?lingo=1&martech=off |
---
- On dev branch, the footer's lang-picker should be working with the url param. On stage it would fail.
---
- Gated by USP so should be very safe
> lingo-poc dynamic link countrified

- express/code/blocks/template-x/template-x.css
- express/code/blocks/template-x/template-x.js
Added a new tworow variant/experiment that can be enabled via page metadata. It will be tested on template pages.
---
Resolves: https://jira.corp.adobe.com/browse/MWPW-155657
---
| Env | URL |
| **Before**  | https://stage--express-milo--adobecom.aem.page/express/templates/flyer?martech=off |
| **After**   | https://template-carousel-2by2--express-milo--adobecom.aem.page/drafts/jingle/template-x-two-rows?martech=off |
---
- Visit the branch url, and the block itself should be functional
---
- Everything should already be guarded through authoring so releasing the PR itself shouldn't cause any effects
- https://template-carousel-2by2--express-milo--adobecom.aem.page/express/templates/flyer?martech=off
> [MWPW-155657][Test] Template-x tworow experiment

- express/code/blocks/discover-cards/discover-cards.css
Adjusted CSS of discovery-cards flip variant in order to pass accessibility tests.
---
Resolves: [MWPW-177677](https://jira.corp.adobe.com/browse/MWPW-177677)
---
| Env | URL |
| **Before**  | https://stage--express-milo--adobecom.aem.page/drafts/maxn/maxn-photo-collage |
| **After**   | https://mwpw-177677--express-milo--adobecom.aem.page/drafts/maxn/maxn-photo-collage?martech=off |
---
- Steps to reproduce the issue
1. Open https://stage--express-milo--adobecom.aem.page/drafts/maxn/maxn-photo-collage
2. Scroll to the section with the flippable discover cards.
3. Run the accessibility text spacing tool.
Tool documented here: https://dylanb.github.io/bookmarklets.html
Tool found here: https://dylanb.github.io/bookmarklets.html
- Steps to view the new feature
1. Open …
> adjusted CSS of discovery-cards flip variant

- express/code/blocks/grid-marquee/grid-marquee.css
- nala/blocks/search-marquee/search-marquee.page.cjs
- nala/blocks/search-marquee/search-marquee.spec.cjs
- nala/blocks/search-marquee/search-marquee.test.cjs
- nala/blocks/template-x/template-x.test.cjs
- test/blocks/search-marquee/mocks/body.html
This work was done here by @maxn-adobe : https://github.com/adobecom/express-milo/pull/610/ for the most part.
- added tests since @maxn-adobe had already merged the code for the fix.
---
Resolves: [MWPW-178663](https://jira.corp.adobe.com/browse/MWPW-178663)
---
| Env | URL |
| **Before**  | https://main--express-milo--adobecom.aem.page/express/templates/poster |
| **After**   | https://MWPW-178663-2--express-milo--adobecom.aem.page/express/templates/poster?martech=off |
---
1. Open https://main--express-milo--adobecom.aem.page/express/templates/poster
2. Notice the Search icon in the search-marquee below the banner does not appear until you scroll down the page. 
Steps to view the new feature
1. Open https://MWPW-178663-2--express-milo--adobecom.aem.page/express/tem …
> MWPW-178663: Template filter search / filter show on pageload
